Àlgebra Lineal Numèrica - Curs 2024/2025 - Óscar Rodríguez

---

# Tema 2: Introducció

Les matrius `numpy` ofereixen diversos avantatges significatius en comparació amb les llistes de llistes a l'hora de treballar amb dades numèriques. Alguns d'ells són:
&nbsp;

**Eficiència en l'emmagatzematge i l'accés:**
* Les matrius `numpy` emmagatzemen els seus elements en un bloc contigu a la memòria, la qual cosa permet un accés més ràpid als elements.
* En canvi, les llistes de llistes poden tenir elements dispersos a la memòria, la qual cosa pot afectar el rendiment.

**Tipus de dades homogenis:**
* Les matrius de `numpy` contenen elements del mateix tipus de dades (per exemple, tots són enters o tots són nombres de coma flotant). Això simplifica les operacions i evita errors inesperats.
* Les llistes de llistes poden contenir elements de diferents tipus de dades.

**Operacions vectoritzades:**
* `numpy` permet fer operacions matemàtiques a tota la matriu sense necessitat de bucles explícits.
* Aquesta capacitat de vectorització millora significativament la velocitat de càlcul.

**Funcions incorporades:**
* `numpy` proporciona una gran varietat de funcions matemàtiques i estadístiques incorporades.
* Això facilita la realització d'operacions comunes sense haver de programar-les manualment.

&nbsp;

## Operacions vectorials amb numpy




### Matrius i arrays

`numpy` té classes específiques que ens poden ser de gran utilitat quan volem treballar amb matrius i vectors. D'aquesta forma, no utilitzarem llistes, sinó que treballarem amb la classe `array`. També, la llibreria numpy podem trobar la classe `matrix` que no és exactament el mateix. De fet, tenim que:

`np.array`:
* És l'estructura de dades més versàtil de numpy.

* Pot representar matrius multidimensionals (incloent-hi vectors, matrius, etc.).

* Pot tenir qualsevol nombre de dimensions.

* S'utilitza per realitzar operacions matricials i càlculs científics en general.


`np.matrix`:
* És una subclasse de `np.array` dissenyada específicament per treballar amb matrius bidimensionals.

* Si crees una matriu utilitzant `np.matrix`, sempre serà bidimensional.

* Proporciona una sintaxi similar a la de d'altres softwares per a operacions matricials.


Tot i que la classe `matrix` sigui més específica el seu ús s'ha tornat menys comú a causa dels avantatges i flexibilitat de la classe `array`. Per aquest motiu, la classe `matrix` es troba en desús i molt probablement [acabarà desapareixent](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html).

### Definició de matrius i vectors:

Podem definir un vector en `numpy` de la següent forma:

```python
vector = np.array(llista_elements)
```

> ###### 🟢 ***Exemple:***
>
> *Volem crear un vector que contingui els 10 primers nombres primers, i.e.*
>
> $$[2,3,5,7,11,13,17,19,23,29]$$
>
> &nbsp;
>
> ***Codi en python:***
>
> ```python
> import numpy as np
>
> # Definim el vector que conté els primers 10 primers:
> primers = np.array([2,3,5,7,11,13,17,19,23,29])
> ```

&nbsp;

❓**Pregunta 1:**

Com podem saber de quin tipus són els elements d'un array de `numpy`?


In [ ]:
import numpy as np

# Definim el vector que conté els primers 10 primers:
primers = np.array([2,3,5,7,11,13,17,19,23,29])

# El printem per pantalla:
print(primers)

# Mirem quin tipus de variable és primers:
print(f"el vector és del tipus {type(primers)}")

# De quin tipus és un element? (Per exemple el primer):
print(f"primers[0] = {primers[0]} i és del tipus {type(primers[0])}")

[ 2  3  5  7 11 13 17 19 23 29]
el vector és del tipus <class 'numpy.ndarray'>
primers[0] = 2 i és del tipus <class 'numpy.int64'>


❓**Pregunta 2:**

I si barregem tipus d'elements?

In [ ]:
import numpy as np

# Definim el vector que conté els primers 10 primers:
primers = np.array([2,3.,5,7,11,13,17,19,23,29]) # Hem substituit 3 per 3.

# El printem per pantalla:
print(primers)

# Mirem quin tipus de variable és primers:
print(f"el vector és del tipus {type(primers)}")

# De quin tipus és un element? (Per exemple el primer):
print(f"primers[0] = {primers[0]} i és del tipus {type(primers[0])}")

[ 2.  3.  5.  7. 11. 13. 17. 19. 23. 29.]
el vector és del tipus <class 'numpy.ndarray'>
primers[0] = 2.0 i és del tipus <class 'numpy.float64'>





> ⚠️ **Atenció!**
>
> A `numpy` els arrays estan disenyats per contenir els elements del mateix tipus de dades. Això significa que, per defecte, triarà el mateix tipus d'element per totes les dades (i aquesta tria es fa de la manera més eficient possible).

Si volem especificar quin tipus de dada volem que tingui un array ho podem fer mitjaçant el apràmetre opcional `dtype`, per exemple:

> ###### 🟢 ***Exemple:***
>
>
> ```python
> import numpy as np
>
> # vector d'enters:
> primers = np.array([2,3,5,7])
>
> # vectors de float64:
> primers = np.array([2,3.,5,7])
>
> # vector de float64:
> primers = np.array([2,3,5,7],dtype=np.float64)
>
> # vector de float32:
> primers = np.array([2,3,5,7],dtype=np.float32)
>
> # vector amb valors de diferent tipus, perdem eficiència, millor evitar-ho!!:
> primers = np.array([2,3.,5,7],dtype=object)
>```

Podem consultar de quin tipus són els elements d'un array amb l'atribut `dtype`:

In [ ]:
import numpy as np

# vector d'enters:
primers = np.array([2,3,5,7])
print(f"l'array {primers} té elements del tipus {primers.dtype}")

# vector de float64:
primers = np.array([2,3.,5,7])
print(f"l'array {primers} té elements del tipus {primers.dtype}")

# vector de float64:
primers = np.array([2,3,5,7],dtype=np.float64)
print(f"l'array {primers} té elements del tipus {primers.dtype}")

# vector de float32:
primers = np.array([2,3,5,7],dtype=np.float32)
print(f"l'array {primers} té elements del tipus {primers.dtype}")

# vector amb valors de diferent tipus, perdem eficiència, millor evitar-ho!!:
primers = np.array([2,3.,5,7],dtype=object)
print(f"l'array {primers} té elements del tipus {primers.dtype}")

l'array [2 3 5 7] té elements del tipus int64
l'array [2. 3. 5. 7.] té elements del tipus float64
l'array [2. 3. 5. 7.] té elements del tipus float64
l'array [2. 3. 5. 7.] té elements del tipus float32
l'array [2 3.0 5 7] té elements del tipus object


&nbsp;

Podem definir una matriu en `numpy` de la següent forma:

```
vector = np.array(llista_de_llistes_d'elements])
```

Veiem un exemple:

> ###### 🟢 ***Exemple:***
>
>*Volem crear la matriu*
>
> $$M = \begin{pmatrix} 1 & 2 & 3\\ 4 & 5 & 6 \\ 7 & 8 & 9\\ 10 & 11 & 12\end{pmatrix}$$
> *i guardar la matriu amb elements del tipus* `float64`.
>
> **Solució:**
>
> ```python
> import numpy as np
>
> # Definim la matriu, la guardarem com float64:
> M = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype=np.float64)
>```

### Dimensions de vectors i matrius:

De cara al que veurem en aquest curs, és important conèixer les dimensions d'un array. Per fer-ho utilitzraem la comanda `shape`

| **Comanda**       | **Descripció**                                                                 | **Exemple**                                                                 | **Resultat**                     |
|-------------------|-------------------------------------------------------------------------------|-----------------------------------------------------------------------------|----------------------------------|
| `shape`           | Retorna la forma (dimensions) d'un array de `numpy`.                           | `arr = np.array([[1, 2, 3], [4, 5, 6]])` <br> `arr.shape`                   | `(2, 3)` (2 files, 3 columnes)  |
|                   | - Per a un array 1D: retorna una tupla amb un sol element (nombre d'elements).| `arr = np.array([1, 2, 3, 4])` <br> `arr.shape`                            | `(4,)` (4 elements)             |
|                   | - Per a un array 2D: retorna una tupla amb (files, columnes).                | `arr = np.array([[1, 2], [3, 4], [5, 6]])` <br> `arr.shape`                | `(3, 2)` (3 files, 2 columnes)  |
|                   | - Per a un array 3D: retorna una tupla amb (dim1, dim2, dim3).               | `arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])` <br> `arr.shape`    | `(2, 2, 2)` (2x2x2)             |


 **Nota:** `shape` és un atribut, no una funció, per tant no s'usa parèntesis `()`

Considerem un exemple:

In [ ]:
import numpy as np

# Definim la matriu, la guardarem com float64:
M = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype=np.float64)

# Mirem les dimensions:
dimensions = np.shape(M)

# Printem el número de files i columnes:
print(f"M té {dimensions[0]} files i {dimensions[1]} columnes")


### Alternativa:
m,n = M.shape
print(f"M té {m} files i {n} columnes")


M té 4 files i 3 columnes
M té 4 files i 3 columnes


> ⚠️ **Atenció!**
>
>  És important no confondre les funcions (o atributs) `ndim`, `shape` i `size` i la funció `len`
>  
>  - `M.shape` o `np.shape(M)` ens dona les dimensions (en l'exemple anterior (4,3), quatres files i tres columnes)
>
>  - `M.ndim` o `np.ndim(M)` ens retorna el número de dimensions (en l'exemple anterior 2, ja que `M` és una matriu)
>
>  - `M.size` o `np.size(M)` ens retorna el nombre d'elements (en l'exemple anterior 12)
>
> - `len(M)` ens retorna el número de files (en l'exemple anterior 4)

&nbsp;


### Matrius i vectors particulars:

Hi ha algunes funcions que ens permeten generar vectors o matrius particulars, algunes de les més usuals són:


| Funció                     | Descripció                                                                 | Exemple d'Ús                                  | Resultat                                      |
|----------------------------|---------------------------------------------------------------------------|-----------------------------------------------|-----------------------------------------------|
| `np.array()`               | Crea un array a partir d'una llista o tupla.                              | `np.array([1, 2, 3])`                         | `[1 2 3]`                                     |
| `np.zeros()`               | Crea un array de zeros.                                                   | `np.zeros(3)`                                 | `[0. 0. 0.]`                                  |
| `np.ones()`                | Crea un array de uns.                                                     | `np.ones((2, 3))`                             | `[[1. 1. 1.], [1. 1. 1.]]`                    |
| `np.empty()`               | Crea un array sense inicialitzar (valors aleatoris de memòria).           | `np.empty((2, 2))`                            | (Contingut no inicialitzat)                   |
| `np.arange()`              | Crea un array amb valors en un interval.                                  | `np.arange(0, 10, 2)`                         | `[0 2 4 6 8]`                                 |
| `np.linspace()`            | Crea un array amb valors espaiats linealment.                             | `np.linspace(0, 1, 5)`                        | `[0.   0.25 0.5  0.75 1.  ]`                  |
| `np.eye()`                 | Crea una matriu identitat.                                                | `np.eye(3)`                                   | `[[1. 0. 0.], [0. 1. 0.], [0. 0. 1.]]`        |
| `np.diag()`                | Crea una matriu diagonal a partir d'un vector.                            | `np.diag([1, 2, 3])`                          | `[[1 0 0], [0 2 0], [0 0 3]]`                 |
| `np.random.random()`       | Crea un array amb valors aleatoris entre 0 i 1.                           | `np.random.random((2, 2))`                    | (Matriu 2x2 amb valors aleatoris)             |
| `np.random.randint()`      | Crea un array amb valors enters aleatoris en un interval.                 | `np.random.randint(0, 10, (3, 3))`            | (Matriu 3x3 amb valors entre 0 i 10)          |
| `np.full()`                | Crea un array amb un valor constant.                                      | `np.full((2, 2), 7)`                          | `[[7 7], [7 7]]`                              |
| `np.tile()`                | Repeteix un array un cert nombre de vegades.                              | `np.tile([1, 2], 3)`                          | `[1 2 1 2 1 2]`                               |
| `np.reshape()`             | Canvia la forma d'un array sense modificar les dades.                     | `np.arange(6).reshape(2, 3)`                  | `[[0 1 2], [3 4 5]]`                          |
| `np.copy()`                | Crea una còpia d'un array.                                                | `np.copy(np.array([1, 2, 3]))`                | `[1 2 3]`                                     |
| `np.fromfunction()`        | Crea un array aplicant una funció a cada índex.                           | `np.fromfunction(lambda i, j: i + j, (3, 3))` | `[[0. 1. 2.], [1. 2. 3.], [2. 3. 4.]]`        |
| `np.meshgrid()`            | Crea matrius de coordenades a partir de vectors.                          | `x, y = np.meshgrid([1, 2], [3, 4])`          | `x = [[1 2], [1 2]]`, `y = [[3 3], [4 4]]`    |
| `np.random.normal()`       | Crea un array amb valors aleatoris d'una distribució normal.              | `np.random.normal(0, 1, (2, 2))`              | (Matriu 2x2 amb valors de distribució normal) |
| `np.random.uniform()`      | Crea un array amb valors aleatoris d'una distribució uniforme.            | `np.random.uniform(0, 1, (2, 2))`             | (Matriu 2x2 amb valors uniformes)             |
| `np.random.rand()`         | Crea un array amb valors aleatoris entre 0 i 1 (forma com a argument).    | `np.random.rand(2, 2)`                        | (Matriu 2x2 amb valors aleatoris)             |
| `np.random.randn()`        | Crea un array amb valors aleatoris de distribució normal estàndard.       | `np.random.randn(2, 2)`                       | (Matriu 2x2 amb valors de distribució normal) |

Algunes d'aquetes funcions permeten paràmetres adicionals que les fan encara més versàtils.

> ⚠️ **Atenció!**
>
> Si tenim que `M` és una matriu i fem `A = M`, la matriu `A` fa referència a `M` i per tant, si modifiquem A també es modificarà l'element de `M`. Podem evitar això fent una copia.

In [ ]:
import numpy as np

# Definim la matriu M i l'escrivim per pantalla:
M = np.eye(2,3)
print(f"M=\n{M}\n")

# Assignem M a A
A = M

# Modifiquem el primer element de A també es modifica el primer element de M
A[0,0] = 2
print(f"Hem modificat M:\nM=\n{M}\n")

M=
[[1. 0. 0.]
 [0. 1. 0.]]

Hem modificat M:
M=
[[2. 0. 0.]
 [0. 1. 0.]]



In [ ]:
import numpy as np

# Definim la matriu M i l'escrivim per pantalla:
M = np.eye(2,3)
print(f"M=\n{M}\n")

# Copiem M
A = M.copy()

# Modifiquem el primer element de A també es modifica el primer element de M
A[0,0] = 2
print(f"No hem modificat M:\nM=\n{M}")

M=
[[1. 0. 0.]
 [0. 1. 0.]]

No hem modificat M:
M=
[[1. 0. 0.]
 [0. 1. 0.]]


&nbsp;


### Indexació de Vectors i Matrius

La indexació en `numpy` permet accedir i manipular elements específics d'un array (vector o matriu) de manera molt senzilla.

#### 1. Indexació bàsica:

**Vectors (1D)**

Per accedir a elements d'un vector, utilitza l'índex entre claudàtors `[]`. La numeració és la mateixa que pel cas de les llistes

```python
import numpy as np

# Definim el vector
vector = np.array([10, 20, 30, 40, 50])

# Accedir al primer element
print(vector[0])  # 10

# Accedir al segon element
print(vector[1])  # 20

# Accedir a l'últim element
print(vector[-1])  # 50

# Accedir al penúltim element
print(vector[-2])  # 40
```

**Matrius (2D)**

Per accedir a leements d'una matriu, a diferència de les llistes de llistes, podem utilitzar la notació `[fila,columna]`

```python
import numpy as np

# Definim la matriu:
matriu = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Accedir a l'element de la segona fila i tercera columna
print(matriu[1,2])  # 6

# Accedir a la primera fila
print(matriu[0,:])  # [1 2 3]

# Accedir a la segona columna
print(matriu[:,1])  # [2 5 8]
```

#### 2. Per tall (*slicing*)

El tall o *slicing* permet extreure subconjunts d'un array.

**Vectors (1D)**

```python
import numpy as np

# Definim el vector:
vector = np.array([10, 20, 30, 40, 50])

# Tall: elements de l'índex 1 al 3 (sense incloure el 3)
print(vector[1:3])  # [20 30]

# Tall: elements des de l'inici fins a l'índex 3
print(vector[:3])  # [10 20 30]

# Tall: elements des de l'índex 2 fins al final
print(vector[2:])  # [30 40 50]
```

**Matrius (2D)**

```python
import numpy as np

# Definim la matriu:
matriu = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Tall: primera i segona fila
print(matriu[:2, :])  # [[1 2 3], [4 5 6]]

# Tall: segona i tercera columna
print(matriu[:, 1:])  # [[2 3], [5 6], [8 9]]

# Tall: submatriu de les dues primeres files i columnes
print(matriu[:2, :2])  # [[1 2], [4 5]]
```

#### 3. Indexació amb arrays boolenas

Podem seleccionar elements basats en una condició:

```python
import numpy as np

# Definim el vector:
vector = np.array([10, 20, 30, 40, 50])

# Condició: elements majors que 30
condicio = vector > 30
print(vector[condicio])  # [40 50]

# També podriem fer directament:
print(vector[vector > 30])  # [40 50]
```


En el cas de matrius, tenim el que es coneix com a màscara:

```python
import numpy as np

# Definim la matriu:
matriu = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Màscara: elements majors que 5
mascara = matriu > 5
print(matriu[mascara])  # [6 7 8 9]
```

#### 4. Indexació amb arrays d'índexs

També podem seleccionar elements específics utilitzants una llista d'índexs:

```python
import numpy as np

# Definim el vector:
vector = np.array([10, 20, 30, 40, 50])

# Seleccionar elements amb índexs 0, 2, i 4
indexs = [0, 2, 4]
print(vector[indexs])  # [10 30 50]
```

Funciona exactament igual per matrius:

```python
import numpy as np

# Definim la matriu:
matriu = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Seleccionar files 0 i 2, i columnes 1 i 2
print(matriu[[0, 2], 1:3])  # [[2 3], [8 9]]
```

&nbsp;

### Operacions bàsiques amb vectors i matrius:

#### Operacions bàsiques amb vectors

Suposem que definim els dos vectors de la mateixa dimensió:

```python
import numpy as np

# Definim els dos vectors:
v1 = np.array([1,2,3])
v2 = np.array([2,3,4])
```
&nbsp;

**Suma de vectors:**

```python
suma = v1+v2 # Suma de v1 i v2 component a component [3,5,7]
```

&nbsp;

**Resta de vectors:**
```python
resta = v1-v2 # Resta de v1 i v2 component a component [-1,-1,-1]
```

&nbsp;

**Producte per un escalar:**
```python
escalar = 2

productePerEscalar = escalar*v1 # Multiplicació del vector per l'escalar
                                # [2,4,6]
```

També podem fer terme a terme les altres operacins bàsiques (com dividir per un escalar (/), elevar cada terme a un nombre (**), etc.)

&nbsp;

**Producte escalar de dos vectors:**

```python
# Opció 1: fem servir la funció np.dot
producteEscalar = np.dot(v1,v2) # 20

# Opció 2: fem servir l'operand @
producteEscalar = v1 @ v2 # 20
```


> ⚠️ **Atenció!**
>
> És important fer servir `@` enlloc de `*` pel producte escalar de dos vectors. Si fem servir `*` obtindrem el producte component a component (o porducte de Hadamard)
> ```python
> v1 * v2 # = [1*2,2*3,3*4] = [2,6,12]
>```

Així, tenim una tercera opció per fer el producte escalar (no recomanada a la pràctica):
```python
# Opció 3 (no recomanada)
producteEscalar = np.sum(v1*v2) # 20
```

&nbsp;

**Producte vectorial de dos vectors (tridimensionals):**
```python
vecprod = np.cross(v1,v2) # Producte vectorial de v1 i v2 [-1,2,-1]
```

&nbsp;

#### Operacions bàsiques amb matrius

Suposem que definim dues matrius de la mateixa dimensió:

```python
import numpy as np

# Definim les dues *matrius*:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,0,0],[0,1,0]])
```
&nbsp;

**Suma de matrius:**

```python
C = A+B # Suma de A i B component a component [[2,2,3],[4,6,6]]
```

&nbsp;

**Resta de matrius:**
```python
D = A-B # Resta de A i B component a component [[0,2,3],[4,4,6]]
```

&nbsp;

**Producte per un escalar:**
```python
escalar = 2

E = escalar*A # Multiplicació de la matriu per l'escalar
              # [[2,4,6],[8,10,12]]
```

&nbsp;

**Producte escalar de dues matrius**

Per poder multiplicar dues matrius amb el producte matricial, necessitem que les seves dimensions siguin coherents. SI volem calcular $AB$ necessitem que A sigui $m\times n$ i $B$ sigui $n\times p$.

```python
# Definim les dues *matrius*:
A = np.array([[1,2],[3,4]])
B = np.array([[1,0,0],[0,1,0]])

# Opció 1: Podem fer el producte amb l'operador @
F = A @ B
# Si fem B @ A ens donarà error per les dimensions!!

# Opció 2: Podem utilitzar la funció np.dot
F = np.dot(A,B)
```


> ⚠️ **Atenció!**
>
> De la mateixa manera que pels vectors, és important fer servir `@` enlloc de `*` pel producte escalar de dues matrius. Si fem servir `*` obtindrem el producte de Hadamart


*Exercici:*

*Implementa una funció que calculi el producte de dues matrius $A$ i $B$ fent les operacions element a element. Si les dimensions no són coherents retornarem un error. És a dir implementa el següent algorisme:*

$
\begin{aligned}
& C = 0\\
& \text{for } i = 0,1,\ldots,n-1\\
& \phantom{for} \text{for } j = 0,1,\ldots,p-1\\
& \phantom{forfor} \text{for } k = 0,1,\ldots,m-1\\
& \phantom{forforfor} c_{ij} \leftarrow c_{ij} + a_{ik}b_{kj}\\
& \phantom{forfor} \text{end for}\\
& \phantom{for} \text{end for}\\
& \text{end for}\\
\end{aligned}
$

emprant el codi

```python
raise ValueError("Dimensions de les matrius incorrectes!")
```
si les dimensions de les matrius no són consistents.

In [9]:
## Espai per fer l'exercici
import numpy as np

def prodMat(A,B):
    # Completar

    n = A.shape[0]
    p = A.shape[1]
    m = B.shape[1]
    
    C = np.zeros((n,m)) 

    if (p != B.shape[0]):
        raise ValueError("Dimensions de les matrius incorrectes!")

    for i in range(n):
        for j in range(p):
            for k in range(m):
                C[i][j] = C[i][j] + A[i][j] * B[i][j]

   
    return C 




*Exercici:*

*Compara l'eficiència de la teva funció amb la de `numpy` per dues matrius de dimensió $200\times200$:*

In [10]:
# Improtem la llibreia time per calcular el temps d'execució
import time

# Generem dues matrius de mida 200x200
A = np.random.randn(200,200)
B = np.random.randn(200,200)


# Mesurem el temps d'execució de la nostra funció:
inici1 = time.time()  # Inici del temporitzador
C = prodMat(A,B)      # Cridem la funció
final1 = time.time()  # Final del temporitzador
temps1 = final1 - inici1 # Temps d'execució


# Mesurem el temps d'execució de la multiplicació de numpy:
inici2 = time.time()  # Inici del temporitzador
C = A@B               # Multipliquem
final2 = time.time()  # Final del temporitzador
temps2 = final2 - inici2 # Temps d'execució


# Mostrem el temps d'execució
print(f"Temps d'execució de la notra funció: {temps1:.6f} segons")
print(f"Temps d'execució de la multiplicació de numpy: {temps2:.6f} segons")

Temps d'execució de la notra funció: 3.755810 segons
Temps d'execució de la multiplicació de numpy: 0.003325 segons


> ⚠️ **Important!**
>
> És millor utilitzar les funcions natives de les llibreries, són molt més eficients.

&nbsp;

#### Altres funcions que poden ser útils:

| **Funció**               | **Descripció**                                                   | **Exemple**                                                   |
|--------------------------|-------------------------------------------------------------------|---------------------------------------------------------------|
| `np.reshape()`            | Canvia la forma (dimensions) d'una matriu sense modificar-ne les dades. | `A = np.array([1, 2, 3, 4, 5, 6])`<br> `A_reshaped = np.reshape(A, (2, 3))` |
| `np.transpose()`          | Transposa una matriu (intercanvia files i columnes).             | `A = np.array([[1, 2], [3, 4]])`<br> `A_transpose = np.transpose(A)` |
| `np.flatten()`            | Converteix una matriu multidimensional en un vector 1D.         | `A = np.array([[1, 2], [3, 4]])`<br> `A_flat = A.flatten()`    |
| `np.concatenate()`        | Uneix dues o més matrius al llarg d'una nova dimensió.           | `A = np.array([[1, 2], [3, 4]])`<br> `B = np.array([[5, 6], [7, 8]])`<br> `C = np.concatenate((A, B), axis=0)` |

&nbsp;

##### *Exercici*

*Feu una funció que, donada una matriu i el vector de termes independents, digui si el sistema és compatible determinat, compatible indeterminat o incompatible.*

*Us pot ser d'ajut:*

* `b.reshape(-1, 1)` *per transformar el vector de termes independents en una matriu de $n$ files i 1 columna*
* *La funció `np.concatenate` (veure taula anterior), haureu d'especificar `axis=1` com a paràmetre de la funció.*
* *La funció `np.linalg.matrix_rank(matriu)` que calcula el rang de la variable `matriu`.*

In [ ]:
## Espai per fer l'exercici
import numpy as np


def tipusSistema(A,b):
    # Completar...

    n = len(b)
    b_reshaped = b.reshape(-1, 1)

    rang1 = np.linalg.matrix_rank(A)

    Aplus = np.concatenate((A,b_reshaped), axis=1)

    rang2 = np.linalg.matrix_rank(Aplus)

    if (rang1 == rang2 == n):
        print("Compatible determinat!")

    elif (rang1 == rang2):
        print("Compatible indeterminat!")
    else:
        print("Incompatible!")



In [22]:
## Espai per testejar la funció anterior:

# Sistema compatible determinat:
A1 = np.array([[2, 1],
               [1, 3]])
b1 = np.array([5, 7])

# Sistema compatible indeterminat
A2 = np.array([[2, 4],
               [1, 2]])
b2 = np.array([6, 3])

# Sistema incompatible
A3 = np.array([[1, 2],
               [2, 4]])
b3 = np.array([5, 5])


tipusSistema(A1,b1)
tipusSistema(A2,b2)
tipusSistema(A3,b3)

Compatible determinat!
Compatible indeterminat!
Incompatible!
