Àlgebra Lineal Numèrica - Curs 2024/2025 - Óscar Rodríguez

---

# Resolució de Sistemes Lineals


En aquesta sessió considerarem alguns casos particulars de sistemes lineals de la forma $A \boldsymbol{x} = \boldsymbol{b}$, on:
* $A\in\mathcal{M}_{n,n}(\mathbb{R})$ és la matriu del sistema,
* $\boldsymbol{x}\in\mathbb{R}^n$ és el vector d'incògnites,
* $\boldsymbol{b}\in\mathbb{R}^n$ és el terme independent.

Així, l'objectiu serà trobar la solució del sistema lineal:

$$
\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{pmatrix}
\begin{pmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{n}
\end{pmatrix}
=
\begin{pmatrix}
b_{1} \\
b_{2} \\
\vdots \\
b_{n}
\end{pmatrix},
$$

és a dir, determinar el valor de $x_1$, $x_2$, $\ldots$, $x_n$.

&nbsp;

## Resolució de sistemes triangulars superiors

Suposem que tenim un sistema lineal
$$
U\boldsymbol{x} = \boldsymbol{b}
$$
on $U$ és una matriu triangular superior amb els termes de la diagonal principal no nuls. És a dir, tenim un sistema de la forma:

$$
\begin{pmatrix}
u_{11} & u_{12} & \cdots & u_{1n} \\
0 & u_{22} & \cdots & u_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & u_{nn}
\end{pmatrix}
\begin{pmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{n}
\end{pmatrix}
=
\begin{pmatrix}
b_{1} \\
b_{2} \\
\vdots \\
b_{n}
\end{pmatrix},
$$

amb $u_{ii}\neq 0$ per $i=1,\ldots,n$.

&nbsp;

Això, és equivalent al sistema d'equacions:

$$
\begin{aligned}
u_{11}x_1 + u_{12}x_2  + \cdots + u_{1n}x_n &= b_1, \\
u_{22}x_2 + \cdots + u_{2n}x_n &= b_2, \\
&\,\,\, \vdots \\
u_{nn}x_n &= b_n.
\end{aligned}
$$

&nbsp;


Per resoldre aquest sistema per substitució endarrere, comencem amb l'última equació $u_{nn}x_n = b_n$, d'on obtenim:

$$x_n = \frac{b_n}{u_{nn}}.$$

&nbsp;

A continuació, substituïm $x_n$ a les equacions anteriors i resolem per a la variable corresponent. Així, per a la penúltima equació obtenim:

$$x_{n-1} = \frac{b_{n-1} - u_{n-1,n}\,x_n}{u_{n-1,n-1}},$$

&nbsp;

D'aquesta manera, un cop coneguts $x_n$, $x_{n-1}$, ...  $x_{i+1}$ podem calcular $x_i$ fent:

$$
\boxed{x_i = \frac{b_i - (u_{i,i+1}x_{i+1} + \ldots + u_{in} x_n)}{u_{ii}}=  \frac{1}{u_{ii}}\left(b_i - \sum_{j=i+1}^n u_{ij} x_{j}\right).}
$$

&nbsp;

### Algorisme de substitució endarrere

Amb aquest procediment obtenim l'algorisme de substitució endarrere:

$
\begin{aligned}
&\texttt{for } i = n \div 1 \\
&\phantom{for } x_i \leftarrow b_i\\
&\phantom{for } \texttt{for } j = i +1 \div n\\
&\phantom{for for } x_i \leftarrow x_i - u_{ij}x_j\\
&\phantom{for } \texttt{end for}\\
&\phantom{for } x_i \leftarrow x_i/u_{ii}\\
&\texttt{end for}
\end{aligned}
$

&nbsp;

**Observació:** Necessitem que el rang de la matriu sigui màxim i, per tant, tots els elements $a_{ii}$ hauran de ser diferents de $0$. Típicament, hi afegirem una condició per comprovar-ho, no mirant que sigui diferent de $0$, sinó que sigui més gran en valor absolut que un cert $\varepsilon$ prou petit.

&nbsp;

### Nombre d'operacions:

Comptem el nombre d'operacions:

* **Sumes i restes:** per cada valor de $\{i,j\}$ en fem una:

$$\sum_{i=1}^n \sum_{j=i+1}^n 1 = \sum_{i=1}^n (n-i) = \sum_{i=1}^{n-1} i =\frac{n(n-1)}{2}.$$

* **Productes:** igual que el cas anterior, un per cada valor de $\{i,j\}$.

* **Divisions:** en fem una per cada valor de $i$, per tant, en fem $n$

&nbsp;

**Nombre total d'operacions:**

$$\underbrace{\frac{n(n-1)}{2}}_{\text{Sumes i restes}} + \underbrace{\frac{n(n-1)}{2}}_{\text{Productes}} + \underbrace{n}_{\text{Divisions}} = n^2$$

### *Exercici 1*

*Implementeu una funció en Python anomenada `triU` que realitzi la substitució endarrere per a una matriu triangular superior:*

`def triU(U, b, tol=1e-10):`

*on*

* `U` *és una matriu triangular superior (és a dir, suposarem que tots els elements sota la diagonal principal són zero).*

* `b` *és un vector de termes independents.*

* `tol` *és un valor de tolerància per a elements diagonals petits. Si un element diagonal és menor que* `tol` *en valor absolut, la funció ha de llançar un error amb el missatge “Element diagonal massa petit!”. Això es pot fer amb el codi:* `raise ValueError("Element diagonal massa petit!")`

*La funció* `triU` *ha de retornar un vector* `x` *que sigui la solució del sistema lineal* `Ux = b`*.*

*A més, la funció ha de retornar els següents errors:*

* *Si la matriu* `U` *no és una matriu quadrada retornarà un error dient: “La matriu és {files}x{columnes} i ha de ser quadrada!” on {files} i {columnes} són el nombre de files i columnes que té la matriu* `U` *respectivament. Feu-ho emprant* `raise ValueError(f"...")`.

* *Si la matriu* `U` *és quadrada però el vector* `b` *té dimensions incompatibles retorneu l'error: “Dimensions incompatibles! (files matriu) {files} != {elements_vector} (elements vector)” on {files} són el nombre de files de la matriu* `U` *i {elements_vector} és el nombre d'elements del vector* `b`*. Feu-ho emprant* `raise ValueError(f"...")`.  


In [8]:
## Espai per fer l'exercici:

import numpy as np

def triU(U, b, tol=1e-10):
    
    n, m = U.shape
    
    #comprovem que les dimensions siguin correctes
    if (n != m):
        raise ValueError(f"La matriu és {n}x{m} i ha de ser quadrada!")
    elif(n != len(b)):
        raise ValueError(f"Dimensions incompatibles! (files matriu) {n} != {len(b)} (elements vector)")

    
        
    x = np.zeros((n))
    
    for i in range(n - 1, -1, -1):
        x[i] = b[i]
        
        for j in range(i + 1, n):
            x[i] -= U[i][j]*x[j]
            
        if (U[i][i] < tol):
            raise ValueError("Element diagonal massa petit!")
            
        x[i] /= U[i][i]
        
    return x



In [ ]:
## Espai per testejar la funció triU:


# Cas de prova 1: Sistema lineal simple
U1 = np.array([[3, 4], [0, 2]],dtype = np.float64)
b1 = np.array([7, 2],dtype = np.float64)
print(triU(U1, b1))  # Aquest hauria de retornar [1, 1]


# Cas de prova 2: Sistema lineal amb més variables
U2 = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]],dtype = np.float64)
b2 = np.array([14, 23, 18],dtype = np.float64)
print(triU(U2, b2))  # Aquest hauria de retornar [1, 2, 3]


# Cas de prova 3: Sistema lineal amb un element diagonal petit
U3 = np.array([[1e-11, 2], [0, 1]],dtype = np.float64)
b3 = np.array([2, 1],dtype = np.float64)
try:
    print(triU(U3, b3))  # Aquest hauria de llançar un error
except ValueError as e:
    print(e)


# Cas de prova 4: Sistema lineal amb dimensions de la matriu incorrectes
U4 = np.array([[1, 2, 3], [0, 1, 1]],dtype = np.float64)
b4 = np.array([2, 1],dtype = np.float64)
try:
    print(triU(U4, b4))  # Aquest hauria de llançar un error
except ValueError as e:
    print(e)


# Cas de prova 5: Sistema lineal amb dimensions incompatibles
U5 = np.array([[1, 5], [0, 2]],dtype = np.float64)
b5 = np.array([2, 1, 3],dtype = np.float64)
try:
    print(triU(U5, b5))  # Aquest hauria de llançar un error
except ValueError as e:
    print(e)

Aquest procediment (i el que veurem a continuació) pot fer-se utilitzant la funció [`solve_triangular`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_triangular.html) del mòdul `linalg` de la llibreria `scipy`.

&nbsp;

## Resolució de sistemes triangulars superiors

Suposem que tenim un sistema lineal
$$
L\boldsymbol{x} = \boldsymbol{b}
$$
on $L$ és una matriu triangular inferior. És a dir, tenim un sistema de la forma:

$$
\begin{pmatrix}
l_{11} &0 & \cdots & 0 \\
l_{21} & l_{22} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
l_{n1} & l_{n2} & \cdots & l_{nn}
\end{pmatrix}
\begin{pmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{n}
\end{pmatrix}
=
\begin{pmatrix}
b_{1} \\
b_{2} \\
\vdots \\
b_{n}
\end{pmatrix},
$$

amb $l_{ii}\neq 0$ per $i=1,\ldots,n$.

&nbsp;

Això, és equivalent al sistema d'equacions:


$$
\begin{array}{ll}
l_{11}x_1  &= b_1, \\
l_{21}x_1 + l_{22}x_2 &= b_2, \\
&\,\, \vdots \\
l_{n1}x_1 + l_{n2}x_2 + \ldots + l_{nn}x_n &= b_n.
\end{array}
$$

&nbsp;


Per resoldre aquest sistema per substitució endavant, comencem amb la primera equació $l_{11}x_1 = b_1$, d'on obtenim:

$$x_1 = \frac{b_1}{l_{11}}.$$

&nbsp;

A continuació, substituïm $x_1$ a les equacions anteriors i resolem per a la variable corresponent. Així, per a la segona equació obtenim:

$$x_{2} = \frac{b_{2} - l_{2,1}\,x_1}{l_{2,2}},$$

&nbsp;

D'aquesta manera, un cop coneguts $x_1$, $x_2$, ...  $x_{i-1}$ podem calcular $x_i$ fent:

$$
\boxed{x_i = \frac{b_i - (l_{i,1}x_{1} + \ldots + l_{i,i-1} x_{i-1})}{l_{ii}}=  \frac{1}{l_{ii}}\left(b_i - \sum_{j=1}^{i-1} l_{ij} x_{j}\right).}
$$

&nbsp;



### *Exercici 2*

*Escriviu l'algorisme de substitució endavant.*

### *Exercici 3*

*Implementeu una funció en Python anomenada triL que realitzi la substitució endavant per a una matriu triangular inferior:*

`def triL(L, b, tol=1e-10)`

*similar a l'exercici 1.*

In [ ]:
# Espai per fer l'exercici
import numpy as np

def triL(L, b, tol=1e-10):
          
    n, m = L.shape
    
    #comprovem que les dimensions siguin correctes
    if (n != m):
        raise ValueError(f"La matriu és {n}x{m} i ha de ser quadrada!")
    elif(n != len(b)):
        raise ValueError(f"Dimensions incompatibles! (files matriu) {n} != {len(b)} (elements vector)")

    
        
    x = np.zeros((n))
    
    for i in range(n):
        x[i] = b[i]
        
        for j in range(i):
            x[i] -= L[i][j]*x[j]
            
        if (L[i][i] < tol):
            raise ValueError("Element diagonal massa petit!")
            
        x[i] /= L[i][i]
        
    return x




: 

In [ ]:
## Espai per testejar la funció triL:

# Cas de prova 1: Matriu triangular inferior regular
L1 = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]],dtype = np.float64)
b1 = np.array([1, 2, 3],dtype = np.float64)
print(triL(L1, b1))  # Hauria de retornar [1, 0, 0]

# Cas de prova 2: Matriu triangular inferior amb valors grans
L2 = np.array([[1e10, 0, 0], [2e10, 1e10, 0], [3e10, 4e10, 1e10]],dtype = np.float64)
b2 = np.array([1e10, 2e10, 3e10],dtype = np.float64)
print(triL(L2, b2))  # Hauria de retornar [1, 0, 0]

# Cas de prova 3: Matriu triangular inferior amb un element diagonal massa petit
L3 = np.array([[1e-12, 0, 0], [2, 1e-12, 0], [3, 4, 1e-12]],dtype = np.float64)
b3 = np.array([1, 2, 3],dtype = np.float64)
try:
    print(triL(L3, b3))
except ValueError as e:
    print(e)  # Hauria de retornar "Element diagonal massa petit!"

# Cas de prova 4: Sistema lineal amb dimensions de la matriu incorrectes
L4 = np.array([[1, 0, 0], [3, 1, 0]],dtype = np.float64)
b4 = np.array([2, 1],dtype = np.float64)
try:
    print(triL(L4, b4))  # Aquest hauria de llançar un error
except ValueError as e:
    print(e)


# Cas de prova 5: Sistema lineal amb dimensions incompatibles
L5 = np.array([[1, 0], [3, 2]],dtype = np.float64)
b5 = np.array([2, 1, 3],dtype = np.float64)
try:
    print(triL(L5, b5))  # Aquest hauria de llançar un error
except ValueError as e:
    print(e)

## Resolució de sistemes diagonals

Considerem el cas ara d'un sistema lineal

$$D \boldsymbol{x} = \boldsymbol{b}$$

on $D$ és una matriu diagonal. És a dir, tenim el sistema:

$$
\begin{pmatrix}
d_{11} &0 & \cdots & 0 \\
0 & d_{22} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & d_{nn}
\end{pmatrix}
\begin{pmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{n}
\end{pmatrix}
=
\begin{pmatrix}
b_{1} \\
b_{2} \\
\vdots \\
b_{n}
\end{pmatrix},
$$

que té per solució
$$
x_i = \frac{b_i}{d_{ii}},
$$
per $i=1,\ldots,n$.

## Mètode de Gauss (sense pivotatge)

El mètode de Gauss consta de dues etapes:

1. Eliminació Gaussiana, passem d'un sistema quadrat a un sistema triangular.

2. Substitució endarrere del nou sistema obtingut de l'apartat anterior.

#### *Exemple d'eliminació Gaussiana*



Suposem que volem resoldre el sistema

$$
\left\{
\begin{aligned}
 x_1 + 2x_2 + 3x_3 & = 4\\
 x_1 + 3x_2 + 5x_3 & = 5\\
2x_1 + 6x_2 + 8x_3 & = 10
\end{aligned}
\right.
$$

Eliminem $x_1$ de la segona i tercera equació restant un cop i dos cops la primera fila respectivament:
$$
\begin{aligned}
F_2 &\leftarrow F_2 - F_1\\
F_3 &\leftarrow F_3 - 2\cdot F_1
\end{aligned}
$$
I obtenim:
$$
\left\{
\begin{aligned}
 x_1 + 2x_2 + 3x_3 & = 4\\
        x_2 + 2x_3 & = 1\\
       2x_2 + 2x_3 & = 2
\end{aligned}
\right.
$$

Elimem ara $x_2$ de la tercera equació restant dos cops la segona fila. És a dir:
$$F_3 \leftarrow F_3 - 2\cdot F_2$$
I obtenim:
$$
\left\{
\begin{aligned}
 x_1 + 2x_2 + 3x_3 & = 4\\
        x_2 + 2x_3 & = 1\\
            - 2x_3 & = 0
\end{aligned}
\right.
$$

I ara ja el podriem resoldre fent substitució endarrere.

&nbsp;

#### *Un exemple una mica més general d'eliminació Gaussiana*



Suposem que tenim el sistema següent:

\begin{align*}
a_{11}^{(1)}x_1 + a_{12}^{(1)}x_2 + a_{13}^{(1)}x_3 &= b_1^{(1)}, \\
a_{21}^{(1)}x_1 + a_{22}^{(1)}x_2 + a_{23}^{(1)}x_3 &= b_2^{(1)}, \\
a_{31}^{(1)}x_1 + a_{32}^{(1)}x_2 + a_{33}^{(1)}x_3 &= b_3^{(1)}.
\end{align*}

El primer pas és eliminar $x_1$ de la segona i tercera equacions. Per això, restarem un múltiple de la primera equació a la segona i tercera equacions de manera que en cancel·li el terme en $x_1$. Aquest múltiple es pot calcular fàcilment com
$$m_{i1} = \frac{a_{i1}^{(1)}}{a_{11}^{(1)}},$$
on $i$ és el número de l'equació (2 o 3 en aquest cas). Així, les noves segona i tercera equacions esdevenen:

\begin{align*}
\overbrace{(a_{21}^{(1)} - m_{21}a_{11}^{(1)})}^{0}x_1 +
\color{blue}{(a_{22}^{(1)} - m_{21}a_{12}^{(1)})}x_2 + \color{Red}{(a_{23}^{(1)} - m_{21}a_{13}^{(1)})}x_3 &= \color{green}{b_2^{(1)} - m_{21}b_1^{(1)}}, \\
\underbrace{(a_{31}^{(1)} - m_{31}a_{11}^{(1)})}_{0}x_1 +
\color{orange}{(a_{32}^{(1)} - m_{31}a_{12}^{(1)})}x_2 + \color{purple}{(a_{33}^{(1)} - m_{31}a_{13}^{(1)})}x_3 &= \color{brown}{b_3^{(1)} - m_{31}b_1^{(1)}}.
\end{align*}

a les quals, per simplificar notació anomenarem
\begin{align*}
\color{blue}{a_{22}^{(2)}}x_2 + \color{red}{a_{23}^{(2)}}x_3 &= \color{green}{b_2^{(2)}}, \\
\color{orange}{a_{32}^{(2)}}x_2 + \color{purple}{a_{33}^{(2)}}x_3 &= \color{brown}{b_3^{(2)}}.
\end{align*}


A continuació, eliminem $x_2$ de la tercera equació restant un múltiple de la segona equació a la tercera. El múltiple es calcula com
$$m_{32} = \frac{a_{32}^{(2)}}{a_{22}^{(2)}}.$$
Així, la nova tercera equació esdevé:
$$
  \underbrace{(a_{33}^{(2)} - m_{32}a_{23}^{(2)})}_{a_{33}^{(3)}}x_3 = \underbrace{b_3^{(2)} - m_{32}b_2^{(2)}}_{b_3^{(3)}}
$$

Per tant, arribem a un sistema triangular, el qual ja sabem resoldre utilitzant el mètode de substitució endarrere:

$$
\begin{pmatrix}
a_{11}^{(1)} & a_{12}^{(1)} & a_{13}^{(1)} \\
0 & a_{22}^{(2)} & a_{23}^{(2)} \\
0 & 0 & a_{33}^{(3)}
\end{pmatrix}
\begin{pmatrix}
x_{1} \\
x_{2} \\
x_{3}
\end{pmatrix}
=
\begin{pmatrix}
b_{1}^{(1)} \\
b_{2}^{(2)} \\
b_{3}^{(3)}
\end{pmatrix}.
$$

&nbsp;

#### Eliminació Gaussiana:

Si denotem per $A^{(1)}:=A$ i $\boldsymbol{b}^{(1)} :=\boldsymbol{b}$ tenim que $A^{(k)}$ i $\boldsymbol{b}^{(k)}$ tenen l'expressió:

$$
A^{(k)}
=
\begin{pmatrix}
a_{11}^{(1)} & a_{12}^{(1)} & \cdots & a_{1k}^{(1)} & \cdots & a_{1n}^{(1)} \\
             & a_{22}^{(2)} & \cdots & a_{2k}^{(2)} & \cdots & a_{2n}^{(2)} \\
             &              & \ddots & \vdots       &        & \vdots       \\
             &              &        & a_{kk}^{(k)} & \cdots & a_{kn}^{(k)} \\
             &              &        & \vdots       &        & \vdots       \\
             &              &        & a_{nk}^{(k)} & \cdots & a_{nn}^{(k)} \\
\end{pmatrix},
\qquad
\boldsymbol{b}^{(k)}
=
\begin{pmatrix}
b_1^{(1)}\\
b_2^{(2)}\\
\vdots \\
b_k^{(k)}\\
\vdots \\
b_n^{(k)}\\
\end{pmatrix}
$$

per $k=2,\ldots, n$. El pas $k$-èssim es fa canviant únicament els valors de les files $k+1$ en endavant de $A^{(k)}$ i $\boldsymbol{b}^{(k)}$:

$$
\left\{
\begin{aligned}
&m_{ik} = \frac{a_{ik}^{(k)}}{a_{kk}^{(k)}}, \quad i = k+1,\ldots, n\\[.5ex]
&b_i^{(k+1)} = b_{i}^{(k)} - m_{ik}b_{k}^{(k)}, \quad i = k+1,\ldots, n\\[.5ex]
&a_{ij}^{(k+1)} = a_{ij}^{(k)} - m_{ik}a_{kj}^{(k)}, \quad i = k+1,\ldots, n,\quad j = k+1,\ldots,n
\end{aligned}
\right.
$$


**Observació 1:** Podem considerar l'index $j$ a  partir de $k+1$, ja que per $j=k$ ja sabem que $a_{ik}^{(k+1)} = 0$ $\forall i = k+1,\ldots, n$.


**Observació 2:** Necessitem que l'element $a_{kk}^{(k)}$ sigui diferent de $0$. De la mateixa manera que pel cas anterior típicament considerarem un valor prou petit com a tolerància per tal de verificar aquesta condició.

&nbsp;

### Algorisme d'eliminació Gaussiana

Amb aquest procediment obtenim l'algorisme d'eliminació Gaussiana:

$
\begin{aligned}
&\texttt{for } k = 1 \div n-1 \\
&\phantom{for } \texttt{for } i = k+1 \div n \\
&\phantom{for for } m_{ik} \leftarrow a_{ik}^{(k)} / a_{kk}^{(k)} \\
&\phantom{for for } b_i^{(k+1)} \leftarrow b_{i}^{(k)} - m_{ik}b_{k}^{(k)}\\
&\phantom{for for } \color{blue}{a_{ik}^{(k+1)} \leftarrow 0}\\
&\phantom{for for } \texttt{for } j = k+1\div n\\
&\phantom{for for for}  a_{ij}^{(k+1)} \leftarrow a_{ij}^{(k)} - m_{ik}a_{kj}^{(k)}\\
&\phantom{for for} \texttt{end for}\\
&\phantom{for } \texttt{end for}\\
&\texttt{end for}
\end{aligned}
$

&nbsp;

In [2]:
import numpy as np

A = np.array([[1, 2, 3], [1, 3, 5], [2, 6, 8]], dtype = np.float64)
b = np.array([4, 5, 10], dtype = np.float64)

n = b.shape[0]


for k in range(0, n - 1):
  for i in range(k + 1, n):
    
    m = A[i, k]/A[k, k]
    b[i] -= m * b[k]

    # Opció 1:
    #for j in range(k,n): # Si comencem j = k fem els 0's a la columna k
    #  A[i,j] -= m*A[k,j]

    # Opció 2:
    A[i, k] = 0
    for j in range(k + 1, n): # Si comencem j = k fem els 0's a la columna k
      A[i, j] -= m * A[k, j]


print(A)
print(b)

[[ 1.  2.  3.]
 [ 0.  1.  2.]
 [ 0.  0. -2.]]
[4. 1. 0.]


### Nombre d'operacions

Comptem el nombre d'operacions:

* **Sumes i restes:** per cada valor de $\{i,j,k\}$ en fem una per un element de la matriu i per cada valor de $\{k,i\}$ en fem una pel terme independent:

$$
\begin{aligned}
\sum_{k=1}^{n-1} \sum_{i=k+1}^n\left( 1 +\sum_{j=k+1}^n 1 \right)
& = \sum_{k=1}^{n-1} \sum_{i=k+1}^n\left( n-k+1 \right) \\
& = \sum_{k=1}^{n-1} (n-k)\left( n-k+1 \right) \\
& = \sum_{k=1}^{n-1} (n-k)^2 + \sum_{k=1}^{n-1} (n-k) \\
& = \sum_{i=1}^{n-1} i^2 + \sum_{i=1}^{n-1} i \\
& = \frac{(n-1)n(2n-1)}{6} + \frac{n(n-1)}{2} \\
& = \frac{n(n^2-1)}{3}
\end{aligned}
$$

* **Productes:** igual que l'apartat anterior.

* **Divisions:** en fem una per cada valor de $\{i,k\}$, per tant:

$$
\sum_{k=1}^{n-1} \sum_{i=k+1}^n 1 = \sum_{k=1}^{n-1} \left( n-k \right) =  \sum_{i=1}^{n-1} i  =  \frac{n(n-1)}{2}
$$

&nbsp;

**Nombre total d'operacions:**

$$\underbrace{\frac{n(n^2-1)}{3}}_{\text{Sumes i restes}} + \underbrace{\frac{n(n^2-1)}{3}}_{\text{Productes}} + \underbrace{\frac{n(n-1)}{2}}_{\text{Divisions}} = \frac{2}{3}n^3 + \frac{1}{2}n^2-\frac{7}{6}n$$

&nbsp;

### *Exercici 4*

*Fes una funció anomenada* `elimGauss(A,b,tol=1.e-10)` *que retorni la matriu i el vector de termes independents després de fer el pas d'eliminació Gaussiana. A més, fes que retorni un missatge d'error en el cas de que el pivot (l'element $a_{kk}^{(k)}$) sigui menor en valor absolut que una certa tolerància donada per* `tol` *dient "El pivot del pas {k} està per sota la tolerància ({tol})". De la mateixa manera, verifiqueu que les dimensions són vàlides (tal com heu fet als exercicis 1 i 3).*

In [1]:
# Espai per fer l'exercici

def elimGauss(A, b, tol=1.e-10):
    
    n, r = A.shape
    
    #comprovem que les dimensions siguin correctes
    if (n != r):
        raise ValueError(f"La matriu és {n}x{r} i ha de ser quadrada!")
    elif(n != len(b)):
        raise ValueError(f"Dimensions incompatibles! (files matriu) {n} != {len(b)} (elements vector)")
        
    
    for k in range(0, n - 1):
        for i in range(k + 1, n):

            if (abs(A[k][k]) < tol):
                raise ValueError(f"El pivot del pas {k} està per sota la tolerància ({tol})")
    
            m = A[i, k]/A[k, k]
            b[i] -= m * b[k]

            # Opció 1:
            #for j in range(k,n): # Si comencem j = k fem els 0's a la columna k
            #  A[i,j] -= m*A[k,j]

            # Opció 2:
            A[i, k] = 0
            for j in range(k + 1, n): # Si comencem j = k fem els 0's a la columna k
                A[i, j] -= m * A[k, j]
            
    return A, b

A = np.array([[1, 2, 3], [1, 3, 5], [2, 6, 8]], dtype = np.float64)
b = np.array([4, 5, 10], dtype = np.float64)

U, v = elimGauss(A, b)


print(U, v)  # Aquest hauria de retornar [1, 2, 3]



NameError: name 'np' is not defined

**Observació:** Un cop implementat el codi de l'exercici 4 ja podeu resoldre alguns sistemes lineals fent l'eliminació Gaussiana i la substitució endarrere de l'exercici 1.

&nbsp;

### *Exercici 5*

*Considereu la matriu quadrada $A= (a_{i,j})_{1\leq i,j\leq n}$ que té per coeficients $a_{ij} = 2^{-|i-j|}$ i el vector $\boldsymbol{b} = (b_i)_{1\leq i\leq n}$ amb $b_i=1$.*

*Resoleu els sistemes lineals $A\boldsymbol{x} = \boldsymbol{b}$ per $n=3,4,\ldots,20$, on $n$ és la dimensió del sistema, emprant les funcions implementades als exercicis 1 i 4.*




In [10]:
# Espai per fer l'exercici
n = 5

# definim la matriu A
A = np.zeros((n,n))

for i in range(n):
    for j in range(n):

        exponent = abs(i - j)
        A[i, j] = 2 ** (exponent * (-1))


b = np.ones(n)

U, c = elimGauss(A, b)

x = triU(U, c)


print(x)





[0.66666667 0.33333333 0.33333333 0.33333333 0.66666667]


<small>Solució: $x_1=x_n=2/3$ , $x_k = 1/3$ per $k=2,\ldots,n-1$.</small>

&nbsp;

❓**Pregunta extra Exercici 5**: Hi ha alguna manera més eficient de resoldre aquests sistemes?