Àlgebra Lineal Numèrica - Curs 2024/2025 - Óscar Rodríguez

---

# Resolució de Sistemes Lineals II


## Propietats de l'eliminació Gaussiana

Cada pas de l'eliminació Gaussiana es pot expressar com un producte de matrius:

*   $A^{(k+1)} = G^{(k)} A^{(k)}$
*   $\boldsymbol{b}^{(k+1)} = G^{(k)} \boldsymbol{b}^{(k)}$

per $k=1\ldots,n-1$ on

$$
G^{(k)} =
\begin{pmatrix}
1 &        & \\
  & &\ddots & \\
  & &       & 1 \\
  & &       & -m_{k+1,k} & 1 & & \\
  & &       &  \vdots    &   & &\ddots & \\
  & &       & -m_{n,k}   &   &  &      & 1
\end{pmatrix},
$$
amb $m_{jk} = \cfrac{a_{jk}^{(k)}}{a_{kk}^{(k)}}$ per $j=k+1,\ldots,n$.


&nbsp;

Veiem, en efecte que

$$
\begin{aligned}
 G^{(1)}A^{(1)} &=
\begin{pmatrix}
1 \\
-m_{21}& 1\\
\vdots & & &\ddots\\
-m_{n1} & & & & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
a_{11}^{(1)} & a_{12}^{(1)} & \cdots & a_{1n}^{(1)}\\
a_{21}^{(1)} & a_{22}^{(1)} & \cdots & a_{2n}^{(1)}\\
\vdots & \vdots &  & \vdots\\
a_{n1}^{(1)} & a_{n2}^{(1)} & \cdots & a_{nn}^{(1)}\\
\end{pmatrix}\\[1.5ex]
& =
\begin{pmatrix}
a_{11}^{(1)} & a_{12}^{(1)} & \cdots & a_{1n}^{(1)}\\
0 & a_{22}^{(1)} - m_{21}a_{12}^{(1)} & \cdots &a_{2n}^{(1)} - m_{21}a_{1n}^{(1)}\\
\vdots & \vdots &  & \vdots\\
0 & a_{n2}^{(1)} - m_{n1}a_{12}^{(1)} & \cdots & a_{nn}^{(1)} - m_{n1}a_{1n}^{(1)}
\end{pmatrix}\\[1.5ex]
& =
\begin{pmatrix}
a_{11}^{(1)} & a_{12}^{(1)} & \cdots & a_{1n}^{(1)}\\
0 & a_{22}^{(2)} & \cdots & a_{2n}^{(2)}\\
\vdots & \vdots &  & \vdots\\
0 & a_{n2}^{(2)} & \cdots & a_{nn}^{(2)}\\
\end{pmatrix}\\[1.5ex]
& = A^{(2)}
\end{aligned}
$$


&nbsp;

i, en general:

$$
\begin{aligned}
 G^{(k)}A^{(k)}
& =
\begin{pmatrix}
1 &        & \\
  & &\ddots & \\
  & &       & 1 \\
  & &       & -m_{k+1,k} & 1 & & \\
  & &       &  \vdots    &   & &\ddots & \\
  & &       & -m_{n,k}   &   &  &      & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
a_{1,1}^{(1)} & a_{1,2}^{(1)} & \cdots & a_{1,k}^{(1)} & a_{1,k+1}^{(1)} & \cdots & a_{1,n}^{(1)} \\
             & a_{2,2}^{(2)} & \cdots & a_{2,k}^{(2)} & a_{2,k+1}^{(2)} & \cdots & a_{2,n}^{(2)} \\
             &              & \ddots & \vdots   & \vdots    &        & \vdots       \\
             &              &        & a_{k,k}^{(k)} & a_{k,k+1}^{(k)} & \cdots & a_{k,n}^{(k)} \\
             &              &        & a_{k+1,k}^{(k)} & a_{k+1,k+1}^{(k)} & \cdots & a_{k+1,n}^{(k)} \\
             &              &        & \vdots       &    \vdots &    & \vdots       \\
             &              &        & a_{n,k}^{(k)} & a_{n,k+1}^{(k)} & \cdots & a_{n,n}^{(k)} \\
\end{pmatrix}\\[2.25ex]
& =
\begin{pmatrix}
a_{1,1}^{(1)} & a_{1,2}^{(1)} & \cdots & a_{1,k}^{(1)} & a_{1,k+1}^{(1)} & \cdots & a_{1,n}^{(1)} \\
             & a_{2,2}^{(2)} & \cdots & a_{2,k}^{(2)} & a_{2,k+1}^{(2)} & \cdots & a_{2,n}^{(2)} \\
             &              & \ddots & \vdots   & \vdots    &        & \vdots       \\
             &              &        & a_{k,k}^{(k)} & a_{k,k+1}^{(k)} & \cdots & a_{k,n}^{(k)} \\
             &              &        &   & a_{k+1,k+1}^{(k)} -m_{k+1,k}a_{k,k+1}^{(k)} & \cdots & a_{k+1,n}^{(k)} -m_{k+1,k}a_{k,n}^{(k)}  \\
             &              &        &   &    \vdots &    & \vdots       \\
             &              &        &   & a_{n,k+1}^{(k)} -m_{n,k}a_{k,k+1}^{(k)}& \cdots & a_{n,n}^{(k)} -m_{n,k}a_{k,n}^{(k)}\\
\end{pmatrix}\\[2.25ex]
& =
\begin{pmatrix}
a_{1,1}^{(1)} & a_{1,2}^{(1)} & \cdots & a_{1,k}^{(1)} & a_{1,k+1}^{(1)} & \cdots & a_{1,n}^{(1)} \\
             & a_{2,2}^{(2)} & \cdots & a_{2,k}^{(2)} & a_{2,k+1}^{(2)} & \cdots & a_{2,n}^{(2)} \\
             &              & \ddots & \vdots   & \vdots    &        & \vdots       \\
             &              &        & a_{k,k}^{(k)} & a_{k,k+1}^{(k)} & \cdots & a_{k,n}^{(k)} \\
             &              &        &   & a_{k+1,k+1}^{(k+1)} & \cdots & a_{k+1,n}^{(k+1)} \\
             & & & &    \vdots &    & \vdots       \\
             & & & & a_{n,k+1}^{(k+1)} & \cdots & a_{n,n}^{(k+1)}
\end{pmatrix}\\[2.25ex]
& =
A^{(k+1)}
\end{aligned}
$$




Per tant, tenim:

$$
A^{(n)}
=
G^{(n-1)} A^{(n-1)} = \underbrace{G^{(n-1)}\cdot \ldots \cdot G^{(1)}}_{\hat{L}} \cdot A^{(1)} = \hat{L} \cdot A^{(1)}
$$

on $\hat{L}$ és una matriu triangular inferior.

Observem dues coses:

1.   $A^{(n)} = U$ és una matriu triangular superior
2.   $ L = \hat{L}^{-1}$ és una matriu traingular inferior

Així podem expressar $A$ com el producte d'una matriu triangular inferior i una matriu triangular superior:

$$A = L\cdot U .$$


&nbsp;


### Expressió de $L$:

Notem que

$$
\left(G^{(k)}\right)^{-1} =
\begin{pmatrix}
1 &        & \\
  & &\ddots & \\
  & &       & 1 \\
  & &       & m_{k+1,k} & 1 & & \\
  & &       &  \vdots    &   & &\ddots & \\
  & &       & m_{n,k}   &   &  &      & 1
\end{pmatrix},
$$

 i que, per definició, sabem que $L = \hat{L}^{-1}$, així:

$$
\begin{aligned}
L &= \hat{L}^{-1} = \left( G^{(n-1)}\cdot \ldots \cdot G^{(1)}\right)^{-1} = \left(G^{(1)}\right)^{-1} \cdot \ldots \cdot \left(G^{(n-1)}\right)^{-1}\\
& = \begin{pmatrix}
1 &        & \\
m_{2,1}  & 1 & \\
\vdots & \ddots & \ddots \\
m_{n,1} & \cdots &m_{n,n-1} & 1
\end{pmatrix}
\end{aligned}
$$

és a dir, $L$ és una matriu diagonal amb uns a la diagonal i que els seus elements són els multiplicadors de l'eliminació Gaussiana.

&nbsp;

## Factorització $LU$:

Així, únicament hem de guardar els multiplicadors dins la matriu $L$.

Observem que com la matriu $L$ conté uns a la diagonal, podem guardar les matrius $L$ i $U$ en una mateixa matriu $M$, tal que $M = L+ U -Id$, és a dir:

$M =
\begin{pmatrix}
a_{1,1}^{(1)} & a_{1,2}^{(1)} & \cdots & a_{1,n-1}^{(1)} & a_{1,n}^{(1)} \\
m_{2,1}             & a_{2,2}^{(2)} & \cdots & a_{2,n-1}^{(2)} & a_{2,n}^{(2)} \\
 \vdots            &  \ddots            & \ddots & \vdots   & \vdots   \\
 m_{n-1,1}            &   \cdots           & m_{n-1,n-2}        & a_{n-1,n-1}^{(n-1)} & a_{n-1,n-1}^{(n-1)}\\
 m_{n,1}            &   \cdots           & m_{n,n-2}        & m_{n,n-1} & a_{n,n}^{(n)}\\
\end{pmatrix}
$

&nbsp;

#### Nombre d'operacions:

El nombre d'operacions de l'algorisme és
$$
\frac{2}{3}n^3 - \frac{n^2}{2} - \frac{n}{6} \approx \frac{2}{3}n^3
$$

*Demostració, exercici: Igual que pel cas de l'eliminació Gaussiana sense comptar les operacions del vector del terme independent.*

&nbsp;

### Resolució de sistemes lineals utilitzant la factorització $LU$

Per resoldre un sistema lineal $A\boldsymbol{x} = \boldsymbol{b}$ utilitzant la factorització $LU$ farem el següent procediment:

1. Factoritzem la matriu $A=LU$

2. Resolem el sistema $L\boldsymbol{y} = \boldsymbol{b}$ utilitzant l'algorisme de substitució endavant.

3. Resolem el sistema $U \boldsymbol{x} = \boldsymbol{y}$ utilitzant l'algorisme de substitució endarrere.





&nbsp;

### *Exercici 2:*

*Considereu la matriu*
$$
 A=\begin{pmatrix}
 1  &  1  &   0  \\
 2  &  0  &   2  \\
 0  &  3  &   3
\end{pmatrix}.
$$

$a)$ *Calculeu la descomposició $LU$ d'$A$ (sense pivotatge).*

$b)$ *Useu l'apartat anterior per calcular $A^{-1}$.*

#### *Resolució: Pissarra*

### *Exercici*

*Fes una funció* `factLU(A, tol = 1.e-10)` *que retorni en una matriu $M=L+U-Id$, la factorització $LU$ de la matriu $A$. Et pot servir adaptar la funció `elimGauss` del dia anterior.*

*A més, si la matriu no és quadrada, retorneu l'error de valor: "La matriu no és quadrada!" ho podeu fer amb el codi:*
```python
raise ValueError("La matriu no és quadrada!")
```

*De la mateixa manera, si el valor de $a_{kk}^{(k)}$ és més petit en valor absolut que* `tol` *retorneu l'error de valor "Pivot massa petit! Matriu (pròxima a) singular!". És a dir, afegiu:*
```python
raise ValueError("Pivot massa petit! Matriu (pròxima a) singular!")
```



In [5]:
import numpy as np

def factLU(A, tol=1.e-10):
    
    n, r = A.shape
    
    #comprovem que les dimensions siguin correctes
    if (n != r):
        raise ValueError(f"La matriu no és quadrada!")
        
    
    for k in range(0, n - 1):
        for i in range(k + 1, n):

            if (abs(A[k][k]) < tol):
                raise ValueError("Pivot massa petit! Matriu (pròxima a) singular!")
    
            m = A[i, k]/A[k, k]

            A[i, k] = m
            for j in range(k + 1, n): # Si comencem j = k fem els 0's a la columna k
                A[i, j] -= m * A[k, j]
            
    return A

A = np.array([[1, 1, 0], [2, 0, 2], [0, 3, 3]], dtype = np.float64)

print(factLU(A))

[[ 1.   1.   0. ]
 [ 2.  -2.   2. ]
 [ 0.  -1.5  6. ]]


*Modifica la funció `triL` del dia anterior de manera que hi hagi un paràmetre opcional anomenat `ones` que, quan `ones=True` presuposi que la matriu d'entrada té uns a la diagonals i no faci la divisió per l'element `L[i,i]`. És a dir, la funció ara serà:*

```python
triL(L, b, ones=False, tol=1.e-10)
```

In [2]:
# Espai per fer l'exercici

def triL(L, b, ones=False, tol=1.e-10):
          
    n, m = L.shape
    
    #comprovem que les dimensions siguin correctes
    if (n != m):
        raise ValueError(f"La matriu és {n}x{m} i ha de ser quadrada!")
    elif(n != len(b)):
        raise ValueError(f"Dimensions incompatibles! (files matriu) {n} != {len(b)} (elements vector)")

    
        
    x = np.zeros((n))
    
    for i in range(n):
        x[i] = b[i]
        
        for j in range(i):
            x[i] -= L[i][j]*x[j]
            
        if (abs(L[i][i]) < tol):
            raise ValueError("Element diagonal massa petit!")
            
        if (not ones): 
            x[i] /= L[i][i]
        
    return x

A = np.array([[1, 1, 0], [0, 3, 2], [0, 0, 3]], dtype = np.float64)
b1 = np.array([1, 2, 3],dtype = np.float64)

print(triL(A,b1))

def triU(U, b, tol=1e-10):
    
    n, m = U.shape
    
    #comprovem que les dimensions siguin correctes
    if (n != m):
        raise ValueError(f"La matriu és {n}x{m} i ha de ser quadrada!")
    elif(n != len(b)):
        raise ValueError(f"Dimensions incompatibles! (files matriu) {n} != {len(b)} (elements vector)")

    
        
    x = np.zeros((n))
    
    for i in range(n - 1, -1, -1):
        x[i] = b[i]
        
        for j in range(i + 1, n):
            x[i] -= U[i][j]*x[j]
            
        if (abs(U[i][i]) < tol):
            raise ValueError("Element diagonal massa petit!")
            
        x[i] /= U[i][i]
        
    return x


[1.         0.66666667 1.        ]



*Fes servir les funcions anteriors per resoldre numèricament l'exemple de factorització $LU$ fet a classe (Exercici 2).*



In [17]:
# Espai per fer l'exercici
import numpy as np

# Matriu exercici 2:
A = np.array([[1,1,0],
              [2,0,2],
              [0,3,3]],dtype=np.float64)

# Cridem a la funció:
M = factLU(A)

# Podem extreure les matrius L i U de M per ferificar que L@U = A:
L = np.tril(M,k=-1)+np.eye(len(M)) # Agafaem els elements per sota la diagonal principal i sumem la matriu identitat
U = np.triu(M) # Agafem els elements de la matriu triangular superior.

# Verifiquem que recuperem A:
print(L@U)

# Completeu el càlcul de la inversa:

n = len(M)

Id = np.identity(n);
Y = np.zeros((n,n))
X = np.zeros((n,n))

for i in range(n):
    Y[:n,i] = triL(L, Id[:n,i])

    
for j in range(n):
    X[:n,j] = triU(U, Y[:n,j])


A = L@U

print(A@X)


[[1. 1. 0.]
 [2. 0. 2.]
 [0. 3. 3.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### *Exercici*

*Considereu el mateix sistema que l'exercici 5 del jupyter notebook anterior. És a dir, la matriu quadrada $A= (a_{i,j})_{1\leq i,j\leq n}$ que té per coeficients $a_{ij} = 2^{-|i-j|}$ i el vector $\boldsymbol{b} = (b_i)_{1\leq i\leq n}$ amb $b_i=1$.*

*Resoleu el sistema lineal $A\boldsymbol{x} = \boldsymbol{b}$ per $n=20$ (on $n$ és la dimensió del sistema) emprant la factorització $LU$.*

In [ ]:
# Espai per fer l'exercici:
import numpy as np

# Matriu i terme independnet del sistema:
n = 20
A = np.fromfunction(lambda i, j: 2**(-np.abs(i - j)), (n, n))
b = np.ones(n)

# Resolució del sistema lineal:




### Exercici 5

*Sigui $A$  una matriu regular  donada. Volem resoldre el sistema lineal $A^2x=b$ i comparem 2 estratègies.*


$a)$ *Calculeu el nombre d'operacions si primer calculem $A^2$ i després resolem el sistema aplicant la descomposició $LU$ a la matriu   $A^2$.*

$b)$ *Calculeu el nombre d'operacions si resolem els sistemes $Ay=b$, $Ax=y$ fent servir (una nova) descomposició $LU$ per a la matriu $A$.*
  
$c)$ *Quina és més eficient?*

Resolució: Pissarra

## Mètode de Doolittle

El mètode de Dollittle ens proporciona un mètode per al càlcul de la factorització $LU$ que no utilitza l'eliminació Gaussiana. El procediment per fer-lo és:

$$
\left\{
\begin{aligned}
& u_{kj} = a_{kj} - \sum_{r=1}^{k-1} l_{kr}u_{rj} \quad \text{ per }j=k,\ldots,n\\
& l_{kk} = 1\\
& l_{ik} = \frac{1}{u_{kk}}\left(a_{ik} - \sum_{r=1}^{k-1}l_{ir}u_{rk}\right) \quad \text{ per } i=k+1,\ldots,n
\end{aligned}
\right.
$$

per $k=1,\ldots,n$.

Observem d'igual forma que per l'algorisme funcioni necessitem que $u_{kk}$ sigui diferent de $0$.


### Algorisme de factorització de Doolittle



L'algorisme de factorització de Doolittle és el següent:

$
\begin{aligned}
&\texttt{for } k = 1 \div n \\
&\phantom{for } \texttt{for } j = k \div n \\
&\phantom{for for } u_{kj} \leftarrow a_{kj} \\
&\phantom{for for } \texttt{for } r = 1 \div k-1\\
&\phantom{for for for}  u_{kj} \leftarrow u_{kj} - l_{kr}u_{rj}\\
&\phantom{for for} \texttt{end for}\\
&\phantom{for } \texttt{end for}\\
&\phantom{for } l_{kk} \leftarrow 1\\
&\phantom{for } \texttt{for } i = k +1 \div n \\
&\phantom{for for } l_{ik} \leftarrow a_{ik} \\
&\phantom{for for } \texttt{for } r = 1 \div k-1\\
&\phantom{for for for}  l_{ik} \leftarrow l_{ik} - l_{ir}u_{rk}\\
&\phantom{for for} \texttt{end for}\\
&\phantom{for for } l_{ik} \leftarrow l_{ik}/u_{kk}\\
&\phantom{for } \texttt{end for}\\
&\texttt{end for}
\end{aligned}
$

&nbsp;

### *Exercici extra*:

*Implementa la factorització de Doolittle.*

In [ ]:
# Espai per fer l'exercici



## Material extra:

Avantatges de la factorització de Doolittle? Mirar punt 5 del següent [enllaç](https://mat.caminos.upm.es/wiki/Factorizaci%C3%B3n_de_Doolittle)

