Àlgebra Lineal Numèrica - Curs 2024/2025 - Óscar Rodríguez

---



# Resolució de Sistemes Lineals III

## Mini-repàs

Recordem que no tota matriu quadrada $A$ amb rang màxim admet una factorització $LU$, és a dir, no sempre podrem escriure $A = LU$. Aquest mateix problema és el que trobem amb l'eliminació Gaussiana si no permetem l'intercanvi de files. **Necessitem que l'element** $a_{kk}^{(k)}\neq 0$.





##### *Exemple:*


*Considerem el sistema $Ax=b$ amb*

$$
A =
\begin{pmatrix}
0 & 0 & 3\\
0 & 1 & 2\\
1 & 1 & 1
\end{pmatrix},
\qquad
b =
\begin{pmatrix}
3 \\ 3 \\ 3
\end{pmatrix},
$$

*el qual sabem que té solució trivial $(1,1,1)$.*

*Fixem-nos que la matriu $A$ no admet una factorització $LU$, ja que l'element $a_{11}=0$.*

*Però si intercanviem la primera i la tercera fila de $A$ definim el mateix sistema i sí que podem fer la factorització. És a dir, podem considerar la matriu*

$$
\hat{A} =
\begin{pmatrix}
1 & 1 & 1\\
0 & 1 & 2\\
0 & 0 & 3
\end{pmatrix},
$$

*la qual pot ser factoritzada com $\hat{A} = LU$. (De fet, en aquest cas $U=\hat{A}$ i $L=Id$ ).*

*Observem també que la matriu $\hat{A}$ es una permutació per files de la matriu $A$, i per tant, tenim:*

$$\hat{A} = P \cdot A$$

*on, en aquest cas*

$$
P =
\begin{pmatrix}
0 & 0 & 1\\ 0 & 1 & 0 \\ 1 & 0 & 0
\end{pmatrix}.
$$



&nbsp;

> 💡**Idea:**
>
>No farem la factorització $LU$ de la matriu $A$. Farem la factorització de la matriu $\hat{A} = P\cdot A$.

&nbsp;

> ⚠️ **Atenció!**
>
> La matriu de permutació $P$ és una matriu ortonormal, i, per tant $P^\top = P^{-1}$ (això ho veurem més endavant).

&nbsp;

❓ **Pregunta natural:** Com trobem la matriu $P$?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*Ho farem internament dins de l'algorisme!*

&nbsp;

❓ **Pregunta no tan natural** Com guardem la matriu $P$?

No cal guardar tota la matriu, podem guardar en un vector la posició de la reordenació que fem de les files de $A$.
Així, per exemple, el vector de permutació pel cas anterior seria $p = (3,2,1)$.

> ⚠️ **Important**
>
>Recordem que en python la indexació comença en $0$, per tant, el vector de permutació seria millor guardar-lo com $(2,1,0)$.

&nbsp;

## Factorització $LU$ amb pivotatge

Comencem amb un exemple motivador... No només és interessant fer l'intercanvi de files quan $a_{kk}^{(k)}\neq 0$.

### *Exercici 12*

*Resoleu el sistema lineal $Ax = b$ treballant només amb 3 digits, on*

$$
A = \begin{pmatrix} -10^{-5} & 1\\ 2 & 1\end{pmatrix}, \qquad b = \begin{pmatrix} 1\\ 0\end{pmatrix}.
$$

*Resoleu ara*

$$
A = \begin{pmatrix} 2 & 1\\ -10^{-5} & 1\end{pmatrix}, \qquad b = \begin{pmatrix} 0\\ 1\end{pmatrix}.
$$

*Calculeu també la solució exacta.*

#### Resolució

Comencem primer de tot calculant la solució de manera exacta:


$$
\left\{
  \begin{aligned}
  x_1 & = -\frac{100000}{200001} \approx - 0.4999975000124999375003124984375078,\\
  x_2 & = \frac{200000}{200001} \approx 0.9999950000249998750006249968750156.
  \end{aligned}
\right.
$$

In [ ]:
# Podem utilitzar la llibreria Sympy per avaluar una expressió amb les xifres que desitgem:
import sympy as sp

# Definim les fraccions:
x1 = sp.Rational(-100000,200001)
x2 = sp.Rational(200000,200001)

# Avaluem els nombres amb les xifres decimals que vulguem, per exemple 30:
x1_approx = x1.evalf(30)
x2_approx = x2.evalf(30)

# Imprimim les solucions i el valor aproximat per pantalla:
print("x1 =",x1,"≈",x1_approx)
print("x2 =",x2,"≈",x2_approx)

x1 = -100000/200001 ≈ -0.499997500012499937500312498438
x2 = 200000/200001 ≈ 0.999995000024999875000624996875


&nbsp;

Fem ara els càlculs pel primer sistema:
$$
\begin{pmatrix}
  -10^{-5} & 1\\
  2 & 1
\end{pmatrix}
\begin{pmatrix}
  x_1\\
  x_2
\end{pmatrix}
=
\begin{pmatrix}
  1\\
  0
\end{pmatrix}
$$
utilitzant 3 dígits i fent l'eliminació Gaussiana.

El resultat que obtenim és (amb 3 xifres significatives) $x_1= 0$, $x_2=1$.


In [ ]:
import decimal as dc

# Treballarem amb 3 xifres:
dc.getcontext().prec = 3

# Coeficients del sistema
a11 = dc.Decimal('-1e-5')
a12 = dc.Decimal('1')
a21 = dc.Decimal('2')
a22 = dc.Decimal('1')

b1 = dc.Decimal('1')
b2 = dc.Decimal('0')


# Procediment (pas per pas) de l'eliminació Gaussiana i la resolució del sistema

# 1) Calculem el multiplicador m21 = a21/a11:
m21 = a21/a11

# 2) Actualitzem a21 i a22:
a21 = a21 - m21*a11 # Això sabem que és 0, ho podríem evitar fer
a22 = a22 - m21*a12 # Actualitzem el valor de a22 de manera usual.

# 3) Actualitzem el valor de b2:
b2 = b2 - m21*b1

# Com és una matriu 2x2 ja hauríem acabat l'eliminació Gaussiana, ara ja podem resoldre el sistema triangular:


# Fem substitució endarrere:
x2 = b2/a22

# Les tres línies següents són equivalents a fer x1 = (b1-a12*x2)/a11
x1 = b1
x1 = x1 - a12*x2
x1 = x1/a11


# Imprimim els resultats
print(f"Solució per x1: {x1:f}")
print(f"Solució per x2: {x2:f}")

Solució per x1: -0
Solució per x2: 1


&nbsp;

Fem ara els càlculs pel segon sistema:
$$
\begin{pmatrix}
    2 & 1\\
  -10^{-5} & 1
\end{pmatrix}
\begin{pmatrix}
  x_1\\
  x_2
\end{pmatrix}
=
\begin{pmatrix}
  0\\
  1
\end{pmatrix}
$$
utilitzant 3 dígits i fent l'eliminació Gaussiana.

El resultat que obtenim és (amb 3 xifres significatives) $x_1= -0.5$, $x_2=1$.

In [ ]:
import decimal as dc

# Treballarem amb 3 xifres:
dc.getcontext().prec = 3

# Coeficients del sistema
a21 = dc.Decimal('-1e-5')
a22 = dc.Decimal('1')
a11 = dc.Decimal('2')
a12 = dc.Decimal('1')

b2 = dc.Decimal('1')
b1 = dc.Decimal('0')


# Procediment (pas per pas) de l'eliminació Gaussiana i la resolució del sistema

# 1) Calculem el multiplicador m21 = a21/a11:
m21 = a21/a11

# 2) Actualitzem a21 i a22:
a21 = a21 - m21*a11 # Això sabem que és 0, ho podríem evitar fer
a22 = a22 - m21*a12 # Actualitzem el valor de a22 de manera usual.

# 3) Actualitzem el valor de b2:
b2 = b2 - m21*b1

# Com és una matriu 2x2 ja hauríem acabat l'eliminació Gaussiana, ara ja podem resoldre el sistema triangular:


# Fem substitució endarrere:
x2 = b2/a22

# Les tres línies següents són equivalents a fer x1 = (b1-a12*x2)/a11
x1 = b1
x1 = x1 - a12*x2
x1 = x1/a11


# Imprimim els resultats
print(f"Solució per x1: {x1:f}")
print(f"Solució per x2: {x2:f}")

Solució per x1: -0.5
Solució per x2: 1


❓ Què està passant?
&nbsp;

&nbsp;

### Pivotatge parcial

Seleccionarem com a pivot l'element $a_{rk}^{(k)}$ tal que $ |a_{rk}^{(k)}|= \displaystyle{\max_{i=k,\ldots,n} |a_{ik}^{(k)}|}$. Intercanviarem les files $r$ i $k$ i, de la mateixa manera, intercanviarem els valors de $p_k$ i $p_r$. En cas d'empat triarem la $r$ més petita.

&nbsp;


### Algorisme de factorització $LU$ amb pivotatge parcial

Suposarem com entrada a l'algorisme una matriu $A$ i volem obtenir la factorització $PA = LU$. El que farem serà reescriure la matriu $A$, de manera que al final de la iteració aquesta sigui igual a $M$ on $M=L+U-Id$.
Així, tenim:

$
\left.
\begin{aligned}
&\texttt{for } k = 1 \div n\\
&\phantom{for } p_k \leftarrow k \\
&\texttt{end for}\\
\end{aligned}
\right\} \text{Inicialitzem el vector de permutacions}
\\
\begin{aligned}
&\texttt{for } k = 1 \div n-1 \\
\end{aligned}\\
\left.
\begin{aligned}
&\phantom{for } i_1 \leftarrow k\\
&\phantom{for } s \leftarrow |a_{kk}|\\
&\phantom{for } \texttt{for } i = k+1 \div n \\
&\phantom{for for } \texttt{if } |a_{ik}| > s \texttt{ then}\\
&\phantom{for for for}  i_1 \leftarrow i\\
&\phantom{for for for}  s \leftarrow |a_{ik}|\\
&\phantom{for for }  \texttt{end if}\\
&\phantom{for } \texttt{end for}\\
\end{aligned}\right\} \text{ Seleccionem el pivot}\\
\left.
\begin{aligned}
&\phantom{for } \texttt{for } j = 1 \div n\\
&\phantom{for for } s \leftarrow a_{i_1 j}\\
&\phantom{for for } a_{i_1 j} \leftarrow a_{k j}\\
&\phantom{for for } a_{k j} \leftarrow s\\
&\phantom{for } \texttt{end for}\\
\end{aligned}
\right\}  \text{ Intercanviem files }\\
\left.
\begin{aligned}
&\phantom{for } r \leftarrow p_{i_1}\\
&\phantom{for } p_{i_1} \leftarrow p_k\\
&\phantom{for } p_k \leftarrow r\\
\end{aligned}\right\} \text{ Actualitzem el vector de permutacions}\\
\begin{aligned}
&\phantom{for } \texttt{for } i = k+1 \div n \\
&\phantom{for for } m \leftarrow a_{ik} / a_{kk}\\
&\phantom{for for } a_{ik} \leftarrow m\\
&\phantom{for for } \texttt{for } j = k+1\div n\\
&\phantom{for for for}  a_{ij} \leftarrow a_{ij} - m\cdot a_{kj}\\
&\phantom{for for} \texttt{end for}\\
&\phantom{for } \texttt{end for}\\
&\texttt{end for}
\end{aligned}
$


&nbsp;

&nbsp;

> ⚠️ **Observació 1**
>
> Podem trobar quin és l'índex de l'element més gran d'un array en `numpy` emprant la funció `argmax()`. En cas d'empat retorna l'índex més petit.
>```python
> index = np.argmax(v) # Retorna l'índex de l'element més gran de v
>```

&nbsp;

> ⚠️ **Observació 2**
>
> Quan permutem files també ho fem amb la $L$ que estem construint, per això el bucle va de $1$ a $n$.

&nbsp;

> ⚠️ **Observació 3**
>
> En python no cal fer un bucle per intercanviar dues files:
> ```python
> M[[j,k]] = M[[k,j]] # Intercanviem les posicions j i k del vector M o les files j i k de la matriu M
>

&nbsp;

### *Exercici 3*

*Donada la matriu*
 $$
A=
\begin{pmatrix}
0 & 1 & 2 & 3\\
3 & 0 & 1 & 2\\
2 & 3 & 0 & 1\\
1 & 2 & 3 & 0
\end{pmatrix}
$$
*triangularitzeu-la aplicant pivotatge parcial, especificant $P$, $L$, $U$.*

*Comproveu que $P A = L U$.*

Pissarra

&nbsp;

### *Exercici*:

*Programeu la factorització $PA = LU$ amb pivotatge parcial. Per fer-ho, creeu la funció*
`LUpivpar(A, tol = 1.e-10)`
*que retorni la matriu* `M` *i el vector de permutacions* `p`. *(Recordeu que $M=L+U-Id$).*

*De la mateixa manera, si la matriu no és quadrada, retorneu l'error de valor: "La matriu no és quadrada!" ho podeu fer amb el codi:*
```python
raise ValueError("La matriu no és quadrada!")
```

*A més, si el valor del pivot seleccionat és més petit en valor absolut que* `tol` *retorneu l'error de valor "Pivot massa petit! Matriu (pròxima a) singular!". És a dir, afegiu:*
```python
raise ValueError("Pivot massa petit! Matriu (pròxima a) singular!")
```

*Podeu fer-ho modificant la funció `factLU` del dia anterior. Comproveu que $PA=LU$ pel cas anterior.*

In [ ]:
## Espai per fer l'exercici








&nbsp;

#### **Pregunta:** És suficient aquesta estratègia de pivotatge?

&nbsp;

### *Exercici 13*

*Resoleu el sistema lineal $Ax = b$ treballant només amb 3 digits, on*

$$
A = \begin{pmatrix} 1 & 10000\\ 1 & 0.0001\end{pmatrix}, \qquad b = \begin{pmatrix} 10000\\ 1\end{pmatrix}.
$$

*Resoleu ara*

$$
A = \begin{pmatrix} 0.0001 & 1\\ 1 & 0.0001\end{pmatrix}, \qquad b = \begin{pmatrix} 1\\ 1\end{pmatrix}.
$$

*Calculeu també la solució exacta.*

#### Resolució

Comencem primer de tot calculant la solució de manera exacta:

$$
  x_1 = x_2 = \frac{10000}{10001} \approx 0.9999000099990000999900009999
$$

In [ ]:
# Podem utilitzar la llibreria Sympy per avaluar una expressió amb les xifres que desitgem:
import sympy as sp

# Definim les fraccions:
x = sp.Rational(10000,10001)


# Avaluem els nombres amb les xifres decimals que vulguem, per exemple 30:
x_approx = x.evalf(30)

# Imprimim la solució i el valor aproximat per pantalla:
print("x1 = x2 =",x,"≈",x_approx)

x1 = x2 = 10000/10001 ≈ 0.999900009999000099990000999900


Fem ara els càlculs pel primer sistema:
$$
\begin{pmatrix}
  1 & 10000\\
  1 & 0.0001
\end{pmatrix}
\begin{pmatrix}
  x_1\\
  x_2
\end{pmatrix}
=
\begin{pmatrix}
  10000\\
  1
\end{pmatrix}
$$
utilitzant 3 dígits i fent l'eliminació Gaussiana.

El resultat que obtenim és (amb 3 xifres significatives) $x_1= 0$, $x_2=1$.


In [ ]:
import decimal as dc

# Treballarem amb 3 xifres:
dc.getcontext().prec = 3

# Coeficients del sistema
a11 = dc.Decimal('1')
a12 = dc.Decimal('10000')
a21 = dc.Decimal('1')
a22 = dc.Decimal('0.0001')

b1 = dc.Decimal('10000')
b2 = dc.Decimal('1')


# Procediment (pas per pas) de l'eliminació Gaussiana i la resolució del sistema

# 1) Calculem el multiplicador m21 = a21/a11:
m21 = a21/a11

# 2) Actualitzem a21 i a22:
a21 = a21 - m21*a11 # Això sabem que és 0, ho podríem evitar fer
a22 = a22 - m21*a12 # Actualitzem el valor de a22 de manera usual.

# 3) Actualitzem el valor de b2:
b2 = b2 - m21*b1

# Com és una matriu 2x2 ja hauríem acabat l'eliminació Gaussiana, ara ja podem resoldre el sistema triangular:


# Fem substitució endarrere:
x2 = b2/a22

# Les tres línies següents són equivalents a fer x1 = (b1-a12*x2)/a11
x1 = b1
x1 = x1 - a12*x2
x1 = x1/a11


# Imprimim els resultats
print(f"Solució per x1: {x1:f}")
print(f"Solució per x2: {x2:f}")

Solució per x1: 0
Solució per x2: 1


&nbsp;

Fixem-nos que al dividir la primera fila per $10000$ obtenim el mateix sistema:

$$
\begin{pmatrix}
  0.0001 & 1\\
  1 & 0.0001
\end{pmatrix}
\begin{pmatrix}
  x_1\\
  x_2
\end{pmatrix}
=
\begin{pmatrix}
  1\\
  1
\end{pmatrix}
$$
utilitzant 3 dígits i fent l'eliminació Gaussiana.

El resultat que obtenim és (amb 3 xifres significatives) $x_1= 0$, $x_2=1$.

In [ ]:
import decimal as dc

# Treballarem amb 3 xifres:
dc.getcontext().prec = 3

# Coeficients del sistema
a11 = dc.Decimal('0.0001')
a12 = dc.Decimal('1')
a21 = dc.Decimal('1')
a22 = dc.Decimal('0.0001')

b1 = dc.Decimal('1')
b2 = dc.Decimal('1')


# Procediment (pas per pas) de l'eliminació Gaussiana i la resolució del sistema

# 1) Calculem el multiplicador m21 = a21/a11:
m21 = a21/a11

# 2) Actualitzem a21 i a22:
a21 = a21 - m21*a11 # Això sabem que és 0, ho podríem evitar fer
a22 = a22 - m21*a12 # Actualitzem el valor de a22 de manera usual.

# 3) Actualitzem el valor de b2:
b2 = b2 - m21*b1

# Com és una matriu 2x2 ja hauríem acabat l'eliminació Gaussiana, ara ja podem resoldre el sistema triangular:


# Fem substitució endarrere:
x2 = b2/a22

# Les tres línies següents són equivalents a fer x1 = (b1-a12*x2)/a11
x1 = b1
x1 = x1 - a12*x2
x1 = x1/a11


# Imprimim els resultats
print(f"Solució per x1: {x1:f}")
print(f"Solució per x2: {x2:f}")

Solució per x1: 0
Solució per x2: 1


Permutem la primera i la segona equació per obtenir el sistema:

$$
\begin{pmatrix}
  1 & 0.0001\\
  0.0001 & 1\\
\end{pmatrix}
\begin{pmatrix}
  x_1\\
  x_2
\end{pmatrix}
=
\begin{pmatrix}
  1\\
  1
\end{pmatrix}
$$

i, de la mateixa manera, utilitzant 3 digits fem l'eliminació Gaussiana.

En aquest cas obtenim  $x_1= 1$, $x_2=1$

In [ ]:
import decimal as dc

# Treballarem amb 3 xifres:
dc.getcontext().prec = 3

# Coeficients del sistema
a11 = dc.Decimal('1')
a12 = dc.Decimal('0.0001')
a21 = dc.Decimal('0.0001')
a22 = dc.Decimal('1')

b1 = dc.Decimal('1')
b2 = dc.Decimal('1')


# Procediment (pas per pas) de l'eliminació Gaussiana i la resolució del sistema

# 1) Calculem el multiplicador m21 = a21/a11:
m21 = a21/a11

# 2) Actualitzem a21 i a22:
a21 = a21 - m21*a11 # Això sabem que és 0, ho podríem evitar fer
a22 = a22 - m21*a12 # Actualitzem el valor de a22 de manera usual.

# 3) Actualitzem el valor de b2:
b2 = b2 - m21*b1

# Com és una matriu 2x2 ja hauríem acabat l'eliminació Gaussiana, ara ja podem resoldre el sistema triangular:


# Fem substitució endarrere:
x2 = b2/a22

# Les tres línies següents són equivalents a fer x1 = (b1-a12*x2)/a11
x1 = b1
x1 = x1 - a12*x2
x1 = x1/a11


# Imprimim els resultats
print(f"Solució per x1: {x1:f}")
print(f"Solució per x2: {x2:f}")

Solució per x1: 1.00
Solució per x2: 1


&nbsp;


## Pivotatge parcial esglaonat

No ens limitem a seleccionar com a pivot l'element més gran en valor absolut, sinó que farem el següent:

Suposem que estem al pas $k$-èssim, i definim $\displaystyle{s_i =  \max_{j=k,\ldots, n} |a_{ij}^{(k)}|}$. Seleccionarem com a pivot l'element $a_{rk}^{(k)}$ que satisfà $\displaystyle{\frac{|a_{rk}^{(k)}|}{s_r} = \max_{i =k,\ldots,n} \frac{|a_{ik}^{(k)}|}{s_i}}$.

En cas d'empat triarem la $r$ més petita.

&nbsp;

&nbsp;

### *Exercici 4*

*Donada la matriu*
$$
  A=\begin{pmatrix}
      1 & 2 & 2 & 4\\
      1 & 2 & 1 & 2\\
      3 & 2 & 0 & 6\\
      4 & 2 & 1 & 1
    \end{pmatrix}
$$

$a)$ *triangularitzeu-la aplicant pivotatge parcial esglaonat, especificant $P$, $L$, $U$.*

$b)$ *Comproveu que $P A = L U$.*

$c)$ *Calculeu $\det A$ a partir de l'apartat anterior.*

$d)$ *Calculeu $A^{-1}$ (tenint en compte la matriu de permutació $P$)*

#### Resolució:

$a$)
Abans de començar, inicialitzem el vector de permutacions:

$$p=(1,2,3,4).$$

Comencem amb el primer pas, $k=1$ (que serà $k=0$ amb la indexació de python).

* Hem de calcular el màxim en valor absolut de cada fila:
$$
\begin{pmatrix}
1 & 2 & 2 & \color{blue}{4}\\
1 & \color{blue}{2} & 1 & 2\\
3 & 2 & 0 & \color{blue}{6}\\
\color{blue}{4} & 2 & 1 & 1
\end{pmatrix}
$$
així tenim $s_1 = 4$, $s_2 = 2$, $s_3 = 6$, $s_4 = 4$.

* Calculem ara quin és l'element de la primera columna que és més gran en valor absolut relatiu a la seva columna. És a dir, volem calcular:
$$
\max_{i=1,\ldots,4} \frac{|a_{i1}|}{s_i} = \max \left\{\frac{1}{\color{blue}{4}},\,\frac{1}{\color{blue}{2}},\,\frac{3}{\color{blue}{6}},\,\frac{4}{\color{blue}{4}}\right\} = \frac{4}{\color{blue}{4}}= 1.
$$

* Així doncs, seleccionarem el $4$ de la quarta fila i, per tant, intercanviem la primera i quarta fila i intercanviem els valors de $p_1$ i $p_4$. D'aquesta forma, obtenim:
$$
\begin{pmatrix}
4 & 2 & 1 & 1\\
1 & 2 & 1 & 2\\
3 & 2 & 0 & 6\\
1 & 2 & 2 & 4
\end{pmatrix},
$$

$$p=(4,2,3,1).$$

* Ara hem d'aplicar el pas d'eliminació Gaussiana i guardar els multiplicadors, és a dir, hem de fer el que ens diu el codi:
$$
\begin{aligned}
&\phantom{for } \texttt{for } i = k+1 \div n \\
&\phantom{for for } m \leftarrow a_{ik} / a_{kk}\\
&\phantom{for for } a_{ik} \leftarrow m\\
&\phantom{for for } \texttt{for } j = k+1\div n\\
&\phantom{for for for} a_{ij} \leftarrow a_{ij} - m\cdot a_{kj}\\
&\phantom{for for} \texttt{end for}\\
&\phantom{for } \texttt{end for}\\
\end{aligned}
$$
Fem-ho en detall per la segona fila ($i=2$):

* Primer de tot calculem el multiplicador $m = \cfrac{a_{21}}{a_{11}} = \cfrac{1}{4}$ i el guardem a la posició $a_{21}$.

* A continuació fem el bucle de les $j$, és a dir, l'eliminació Gaussiana:
$$
\begin{aligned}
a_{22} &\leftarrow a_{22} - m\cdot a_{12} = 2 - \frac{1}{4}\cdot 2 = \frac{3}{2}\qquad\text{ (Cas $k=1$, $i =2$, $j = 2$)}\\
a_{23} &\leftarrow a_{23} - m\cdot a_{13} = 1 - \frac{1}{4}\cdot 1 = \frac{3}{4}\qquad\text{ (Cas $k=1$, $i =2$, $j = 3$)}\\
a_{24} &\leftarrow a_{24} - m\cdot a_{14} = 2 - \frac{1}{4}\cdot 1 = \frac{7}{4}\qquad\text{ (Cas $k=1$, $i =2$, $j = 4$)}\\
\end{aligned}
$$

* Repetint el mateix procediment per la tercera i quarta files obtenim:
$$
\begin{pmatrix}
\color{green}{4} & \color{green}{2} & \color{green}{1} & \color{green}{1}\\
\color{blue}{\cfrac{1}{4}} & \color{purple}{\cfrac{3}{2}} & \color{purple}{\cfrac{3}{4}} & \color{purple}{\cfrac{7}{4}}\\
\color{blue}{\cfrac{3}{4}} & \color{purple}{\cfrac{1}{2}} & \color{purple}{-\cfrac{3}{4}} & \color{purple}{\cfrac{21}{4}}\\
\color{blue}{\cfrac{1}{4}} & \color{purple}{\cfrac{3}{2}} & \color{purple}{\cfrac{7}{4}} & \color{purple}{\cfrac{15}{4}}
\end{pmatrix}
$$
En verd tenim els elements definitius, que ja no canviaran al que resta d'algorisme, en blau els multiplicadors i en lila els elements que encara han d'intervenir tant en la selecció de pivotatge com en l'eliminació Gaussiana. Notem que els elements en blau poden patir reordenacions en seleccionar el pivot en el successiu (o successius) passos.

Continuem amb el pas $k=2$:

* Calculem el màxim de cada fila dels elements de la submatriu anterior en lila:
$$
\left(
\begin{aligned}
\begin{array}{c|ccc}
4 & 2 & 1 & 1\\ \hline
\cfrac{1}{4} & \cfrac{3}{2} & \cfrac{3}{4} & \color{blue}{\cfrac{7}{4}}\\
\cfrac{3}{4} & \cfrac{1}{2} & -\cfrac{3}{4} & \color{blue}{\cfrac{21}{4}}\\
\cfrac{1}{4} & \cfrac{3}{2} & \cfrac{7}{4} & \color{blue}{\cfrac{15}{4}}
\end{array}
\end{aligned}
\right)
$$
així tenim $s_2 = \cfrac{7}{4}$, $s_3 = \cfrac{21}{4}$, $s_4 = \cfrac{15}{4}$.

* Busquem ara el pivot seleccionant l'element de la primera columna de la submatriu inferior que té un valor més gran (en valor absolut) relatiu a la seva fila. És a dir, volem calcular:
$$
\max_{i=2,3,4} \frac{|a_{i2}|}{s_i} = \max \left\{\frac{3/2}{\color{blue}{7/4}},\,\frac{1/2}{\color{blue}{21/4}},\,\frac{3/2}{\color{blue}{15/4}}\right\} = \frac{3/2}{\color{blue}{7/4}}= \frac{6}{7}.
$$
Així doncs, en aquest cas no hem d'intercanviar files.

* Fem ara l'eliminació Gaussiana i arribem a:
$$
\begin{pmatrix}
\color{green}{4} & \color{green}{2} & \color{green}{1} & \color{green}{1}\\
\color{green}{\cfrac{1}{4}} & \color{green}{\cfrac{3}{2}} & \color{green}{\cfrac{3}{4}} & \color{green}{\cfrac{7}{4}}\\
\cfrac{3}{4} & \color{blue}{\cfrac{1}{3}} & \color{purple}{-1} & \color{purple}{\cfrac{14}{3}}\\
\cfrac{1}{4} & \color{blue}{1} & \color{purple}{1} & \color{purple}{2}
\end{pmatrix}
$$
En verd tenim els elements definitius, que ja no canviaran al que resta d'algorisme, en blau els multiplicadors i en lila els elements que encara han d'intervenir tant en la selecció de pivotatge com en l'eliminació Gaussiana.

Procedim amb l'últim pas de l'algorisme, $k=3$:

* Podem calcular ràpidament els valors de $s_i$ per $i=3,4$:
$$
\begin{aligned}
s_3 &= \max\left\{1,\,\cfrac{14}{3}\right\} = \frac{14}{3},\\
s_4 &= \max\left\{1,\,2\right\} = 2.
\end{aligned}
$$

* D'aquesta manera hem de seleccionar el màxim:
$$\max_{i=3,4} \frac{|a_{i3}|}{s_i} = \max\left\{\frac{1}{14/3},\,\cfrac{1}{2}\right\} = \frac{1}{2}$$

* Per tant, seleccionarem com a pivot l'element $1$ de la quarta columna i, en conseqüència, hem d'intercanviar les files tres i quatre i el valor de $p_3$ i $p_4$:
$$
\begin{pmatrix}
4 & 2 & 1 & 1\\
\cfrac{1}{4} & \cfrac{3}{2} & \cfrac{3}{4} & \cfrac{7}{4}\\
\cfrac{1}{4} & 1 & 1 & 2 \\
\cfrac{3}{4} & \cfrac{1}{3} & -1 & \cfrac{14}{3}
\end{pmatrix},
$$

$$p=(4,2,1,3).$$

* Fem l'últim pas de l'eliminació Gaussiana i obtenim:
$$
M =
\begin{pmatrix}
4 & 2 & 1 & 1\\
\cfrac{1}{4} & \cfrac{3}{2} & \cfrac{3}{4} & \cfrac{7}{4}\\
\cfrac{1}{4} & 1 & 1 & 2 \\
\cfrac{3}{4} & \cfrac{1}{3} & \color{blue}{-1} & \color{purple}{\cfrac{20}{3}}
\end{pmatrix},
$$
on en blau tenim el multiplicador i en lila el resultat de l'eliminació Gaussiana.

Recordem que, a partir de la matriu $M$ podem construir fàcilment les matrius $L$ i $U$:
$$
L =
\begin{pmatrix}
1 & 0 & 0 & 0\\
\cfrac{1}{4} & 1 & 0 & 0\\
\cfrac{1}{4} & 1 & 1 & 0 \\
\cfrac{3}{4} & \cfrac{1}{3} & -1 & 1
\end{pmatrix},
\qquad
U =
\begin{pmatrix}
4 & 2 & 1 & 1\\
0 & \cfrac{3}{2} & \cfrac{3}{4} & \cfrac{7}{4}\\
0 & 0 & 1 & 2 \\
0 & 0 & 0 & \cfrac{20}{3}
\end{pmatrix}.
$$

A partir del vector de permutacions, podem construir la matriu $P$:

$$
P =
\begin{pmatrix}
0 & 0 & 0 & 1\\
0 & 1 & 0 & 0\\
1 & 0 & 0 & 0\\
0 & 0 & 1 & 0\\
\end{pmatrix}.
$$

$b$) Comprovem, en efecte, que $PA = LU$ ho farem amb `sympy`:

In [ ]:
## Codi per fer la comprovació

# Importem SymPy com sp:
import sympy as sp

# Definim la matriu A:
A = sp.Matrix([[1, 2, 2, 4],[1, 2, 1, 2], [3, 2, 0, 6], [4, 2, 1, 1]])

# Definim el vector de permutacions:
p = [3,1,0,2] # En python l'indexació comença des de 0

# Definim la matriu P
P = sp.Matrix([[int(i == j) for j in range(len(p))] for i in p])


# Definim M
M = sp.Matrix([[4, 2, 1, 1],
               [sp.Rational(1,4), sp.Rational(3,2), sp.Rational(3,4), sp.Rational(7,4)],
               [sp.Rational(1,4), 1, 1, 2],
               [sp.Rational(3,4), sp.Rational(1,3), -1, sp.Rational(20,3)]])

# Extraiem L:
L = M.lower_triangular(-1)+sp.eye(len(p)) # Extreim els elements per sota la diagonal i li sumem la identitat

# Extraiem U:
U = M.upper_triangular(0) # Extraiem els elements per sobre i a la diagonal

# Si fem PA-LU ha de donar la matriu tota 0's:
P@A-L@U

#M.lower_triangular(1)


Matrix([
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]])

Podem fer un codi similar amb numpy

In [ ]:
import numpy as np

# Definim la matriu A
A = np.array([[1, 2, 2, 4], [1, 2, 1, 2], [3, 2, 0, 6], [4, 2, 1, 1]], dtype=np.float64)

# Definim el vector de permutacions
p = np.array([3, 1, 0, 2])

# Creem la matriu P
P = np.eye(len(p))[p]

# Definim la matriu M
M = np.array([[4, 2, 1, 1],
              [1/4, 3/2, 3/4, 7/4],
              [1/4, 1, 1, 2],
              [3/4, 1/3, -1, 20/3]], dtype=np.float64)

# Extraiem L
L = np.tril(M, k=-1) + np.eye(len(p))

# Extraiem U
U = np.triu(M)

# Verifiquem el resultat PA-LU
result = np.matmul(P, A) - np.matmul(L, U) # També podriem utilitzar @
print("Resultat de PA-LU:")
print(result)

Resultat de PA-LU:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


&nbsp;

$c$) Per calcular el determinant d'$A$ recordem que
$$
\det(A) = \det(P^{-1}\cdot L\cdot U) = \det(P^{-1})\cdot\det(L)\cdot\det(U),
$$
i tenim:

* El valor de $\det(P^{-1}) = \det(P) = \pm 1$, ja que es tracta d'una matriu de permutació. En particular, el seu valor serà:
$$
\det(P^{-1}) = \det(P) = (-1)^{q}
$$
on $q$ és el nombre de canvis de files que hem fet durant la factorització, en aquest cas $2$ (hem canviat files a $k=1$ i $k=3$). Per tant el determinant de $P$ i $P^{-1}$ val $1$.

* El determinant de $L$ és 1, ja que és una matriu triangular amb $1$'s a la diagonal.

* El determinant de $U$, al ser triangular, és el producte dels elements que apareixen a la diagonal. Així:
$$
\det(U) = 4\cdot\frac{3}{2}\cdot1\cdot\frac{20}{3} = 40.
$$

Per tant,
$\det(A) = 1\cdot1\cdot40 = 40$.

&nbsp;

&nbsp;

En general, sempre podem utilitzar directament la fórmula

$$\det(A) = (-1)^q\cdot\det(U),$$

on $q$ és el nombre de canvis de files que hem fet durant la factorització.

Això és equivalent a

$$\det(A) = \text{sgn}(p)\cdot\det(U),$$

on $\text{sgn}(p)$ és el [signe del vector permutació](https://encyclopediaofmath.org/wiki/Signature_(permutation)#:~:text=The%20sign%20or%20signature%20of%20a%20permutation%20of,even%20and%20those%20with%20sign%20%24-1%24%20are%20odd.).

In [ ]:
# Suposem que hem executat la cel·la anterior
# (és a dir tenim la llibreria numpy importada i les matrius definides):

print(f"det(P) = {np.linalg.det(P)}")
print(f"det(L) = {np.linalg.det(L)}")
print(f"det(U) = {np.linalg.det(U)}")
print(f"det(A) = {np.linalg.det(A)}")

det(P) = 1.0
det(L) = 1.0
det(U) = 40.0
det(A) = 40.0


&nbsp;

&nbsp;

$d$) Per calcular la inversa d'una matriu hem de resoldre el sistema lineal:

$$A\cdot X = Id$$

(on $X$ és una matriu quadrada $n\times n$, i per tant és equivalent a resoldre $n$ sistemes lineals).

Com tenim la factorització $PA=LU$ això és equivalent a resoldre:
$$LU X = P$$



In [ ]:
# Reosldrem el sistema suposant que ja tenim la descomposició LU:
import numpy as np
from scipy.linalg import solve_triangular # Utilitzarem solve_triangular per resoldre el sistema lineal triangular

############### DADES QUE JA TENIM DE LA FACTORITZACIÓ PA = LU #################

# Definim la matriu A
A = np.array([[1, 2, 2, 4], [1, 2, 1, 2], [3, 2, 0, 6], [4, 2, 1, 1]], dtype=np.float64)

# Definim el vector de permutacions
p = np.array([3, 1, 0, 2])

# Creem la matriu P
P = np.eye(len(p))[p]

# Definim la matriu M
M = np.array([[4, 2, 1, 1],
              [1/4, 3/2, 3/4, 7/4],
              [1/4, 1, 1, 2],
              [3/4, 1/3, -1, 20/3]], dtype=np.float64)

# Extraiem L
L = np.tril(M, k=-1) + np.eye(len(p))

# Extraiem U
U = np.triu(M)

############################### OPCIO 1 ########################################

# Dimensió del sistema:
n = len(p)

invA = np.empty((n, n), dtype=np.float64)

for k in range(n):

  # El vector de termes independents és la k-èsima columna de invP
  b = P[:,k]

  # Resolem el sistema L y = b
  y = solve_triangular(L, b, lower=True)

  # Resolem el sistema U x = y, ho guardem ja a la k-èsima columna de invA
  invA[:,k] = solve_triangular(U,y)


print("Opció 1 - La inversa de A és:")
print(invA)




############################### OPCIO 2 ########################################

# scipy ens permet treballar directament amb la matriu M, no hem de definir L i U :)

# Dimensió del sistema:
n = len(p)

invA = np.empty((n, n), dtype=np.float64)

for k in range(n):

  # El vector de termes independents és la k-èsima columna de invP
  b = P[:,k]

  # Resolem el sistema L y = b
  y = solve_triangular(M, b, lower=True, unit_diagonal=True)

  # Resolem el sistema U x = y, ho guardem ja a la k-èsima columna de invA
  invA[:,k] = solve_triangular(M,y)


print("\n Opció 2 - La inversa de A és:")
print(invA)





########################## EN EFECTE ÉS LA MATRIU INVERSA ######################

print("\nA^{-1}*A:")
print(invA@A)

Opció 1 - La inversa de A és:
[[ 0.05  -0.4    0.05   0.3  ]
 [-0.525  1.2   -0.025 -0.15 ]
 [ 0.7   -0.6   -0.3    0.2  ]
 [ 0.15  -0.2    0.15  -0.1  ]]

 Opció 2 - La inversa de A és:
[[ 0.05  -0.4    0.05   0.3  ]
 [-0.525  1.2   -0.025 -0.15 ]
 [ 0.7   -0.6   -0.3    0.2  ]
 [ 0.15  -0.2    0.15  -0.1  ]]

A^{-1}*A:
[[ 1.00000000e+00  0.00000000e+00 -5.55111512e-17 -5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00  1.38777878e-16  1.38777878e-16]
 [-1.11022302e-16 -2.77555756e-16  1.00000000e+00 -3.05311332e-16]
 [ 5.55111512e-17  2.77555756e-17  1.38777878e-17  1.00000000e+00]]


&nbsp;

### Exercici:

*Programeu la factorització $PA = LU$ amb pivotatge parcial esglaonat. Per fer-ho, creeu la funció*
`LUpivesg(A, tol = 1.e-10)`
*que retorni la matriu* `M` *i el vector de permutacions* `p`. *(Recordeu que $M=L+U-Id$).*

*De la mateixa manera, si la matriu no és quadrada, retorneu l'error de valor: "La matriu no és quadrada!" ho podeu fer amb el codi:*
```python
raise ValueError("La matriu no és quadrada!")
```

*A més, si el valor del pivot seleccionat és més petit en valor absolut que* `tol` *retorneu l'error de valor "Pivot massa petit! Matriu (pròxima a) singular!". És a dir, afegiu:*
```python
raise ValueError("Pivot massa petit! Matriu (pròxima a) singular!")
```

> ⚠️ **Et pot ser d'ajut!**
>
> Pots calcular el valor màxim de cada fila d'una matriu `M` emprant el codi:
>
> ```python
> ss = np.max(M, axis=1)
>```

In [ ]:
## Espai per fer l'exercici:






*Un cop programat, fes el càlcul de la matriu invera de l'Exercici 4 emprant la teva factorització $LU$ amb pivotatge parcial esglaonat:*

In [ ]:
## Espai per fer l'exercici:



