Àlgebra Lineal Numèrica - Curs 2024/2025 - Óscar Rodríguez

---

# VAPs i VEPs: Mètode de Jacobi

### Preliminars:

#### **Matrius de Rotació**

Una matriu de rotació és la matriu que representa una rotació a l'espai euclidià.


&nbsp;

**Al pla:**

En dues dimension, una matriu de rotació té la següent forma:

$$
R(\theta) = \begin{pmatrix}\cos\theta & -\sin\theta\\ \sin\theta & \cos\theta\end{pmatrix}.
$$

&nbsp;

**A l'espai:**

En tres dimension, podem definir les matrius de rotació al voltant dels eixos $x$, $y$ i $z$ facilment:

$$
R_x(\theta) = \begin{pmatrix}1 & 0 & 0\\ 0 & \cos\theta & -\sin\theta\\ 0 & \sin\theta & \cos\theta\end{pmatrix},
$$

$$
R_y(\theta) = \begin{pmatrix}\cos\theta & 0 & \sin\theta\\ 0 & 1 & 0\\ -\sin\theta & 0 & \cos\theta\end{pmatrix},
$$

$$
R_z(\theta) = \begin{pmatrix}\cos\theta & -\sin\theta & 0\\ \sin\theta & \cos\theta & 0\\ 0 & 0 & 1\end{pmatrix}.
$$

&nbsp;

**A l'espai $\mathbb{R}^n$:**

D'igual, forma, podem definir una rotació en el pla $(p,q)$ com la matriu $R_{pq}(\theta)$ de dimensió $n\times n$ que és la identitat excepte als elements

$$
\left\{
\begin{aligned}
&r_{pp} = r_{qq} = \cos\theta\\
&r_{pq} = -r_{qp}  = -\sin\theta
\end{aligned}
\right.
$$

És a dir, tenim la matriu:


$$
R_{p,q}(\theta) = \begin{pmatrix} 1\\ & \ddots\\ & & 1 \\ & & & \cos\theta & & & & -\sin\theta\\
& & & & 1\\
& & & & & \ddots\\
& & & & & & 1\\
& & & \sin\theta & & & & \cos\theta\\
& & & & & & & & 1\\
& & & & & & & & & \ddots\\
& & & & & & & & & & 1\end{pmatrix}
$$.


&nbsp;

**Observació 1:** Si multipliquem una matriu $A$ per una matriu de rotació $R_{p,q}(\theta)$ només modifiquem les seves files $p$ i $q$.


&nbsp;

**Observació 2:** També és possible definir la rotació en un pla arbitrari, però no ho tractarem.

&nbsp;

**Observació 3:** Podeu deduïr les fòrmules trigonomètriques clàsiques a partir de les matrius de rotació.

&nbsp;

##### **Propietats de les matrius de rotació:**

Les matrius de rotació són ortonormals, en particular, tenim:

* $\big(R_{pq}(\theta)\big)^{-1} = \big(R_{pq}(\theta)\big)^\top = R_{pq}(-\theta)$

* $\det(R_{pq}(\theta)) = 1$

&nbsp;

#### **Matrius semblants**

##### **Definició:** Matrius semblants

Donades dues matrius $A$ i $B$ de dimensió $n\times n$ direm que són semblants si existeix alguna matriu invertible $P$ tal que:

$$B=P^{-1}AP$$

##### **Propietats:** de les matrius semblants

Si $\boldsymbol{v}$ és un vector propi de $A$ amb valor propi $\lambda$, aleshores $P^{-1} \boldsymbol{v}$ és un vector propi de $B$ amb valor propi $\lambda$.

&nbsp;

&nbsp;

#### **Diagonalització de matrius simètriques**

##### **Teorema:**

Una matriu $A\in\mathcal{M}_n(\mathbb{R})$ és simètrica si i només $A$ és diagonalitzable i els seus vectors propis són ortogonals.

&nbsp;

## **Mètode de Jacobi**

El mètode de Jacobi és un mètode per al càlcul de valors propis i els seus vectors propis per a matrius simètriques basat en transformacions de semblança.

Així doncs, l'objectiu serà transformar la matriu A més senzilla (diagonal) de manera que sigui immediat calcular els seu valors propis i el seus vectors propis.

### Idea del mètode

Com treballarem amb $A\in\mathcal{M}_n(\mathbb{R})$ simètrica, sabem que existirà una matriu $P$, ortonormal, tal que:

$$
D = P^{-1}AP
$$

on $D$ és una matriu diagonal, que contindrà els valor propis i $P$ és una matriu (ortonormal) que té els vectors propis de $A$ per columnes.

&nbsp;

Fixem-nos que com $P$ és ortonormal, tenim que $P^{-1} = P^\top$ i, per tant, $P^\top P = Id$. D'aquesta forma, podem escriure:

$$
\underbrace{\begin{pmatrix} \lambda_1\\ & \lambda_2\\ & & \ddots \\ & & & \lambda_n\end{pmatrix}}_{D} = \underbrace{\begin{pmatrix}\longleftarrow & \boldsymbol{v}_1 & \longrightarrow\\\longleftarrow & \boldsymbol{v}_2 & \longrightarrow\\ & \vdots \\ \longleftarrow & \boldsymbol{v}_n & \longrightarrow\\ \end{pmatrix}}_{P^\top} A \underbrace{\begin{pmatrix}\Big\uparrow & \Big\uparrow & &\Big\uparrow\\ \boldsymbol{v}_1 & \boldsymbol{v}_2 & \cdots & \boldsymbol{v}_n\\ \Big\downarrow & \Big\downarrow & & \Big\downarrow\end{pmatrix}}_{P}
$$

on els vector $\boldsymbol{v}_i$ són els vectors propis associats al valor propi $\lambda_i$ tals que $\|\boldsymbol{v}_i\| = 1$, $\forall i = 1,\ldots,n$.

&nbsp;

La idea del mètode serà construir la matriu $P$ com a producte de matrius de rotació. Així doncs, el que farem és considerar la següent seqüència de matrius:

$$
\left\{
\begin{aligned}
A^{(1)} &= Q_1^\top A Q_1\\
A^{(2)} &= Q_2^\top A^{(1)} Q_2 = Q_2^\top Q_1^\top A \underbrace{Q_1 Q_2}_{=:\tilde{Q}_2}\\
\vdots\\
A^{(k)} & = Q_{k}^\top A^{(k-1)} Q_{k} = \left(\prod_{i=1}^kQ_{i}^\top\right) A \underbrace{\left(\prod_{i=1}^kQ_{i}\right)}_{=:\tilde{Q}_k}
\end{aligned}
\right.    
$$

on les $Q_i$ són matrius de rotació i que les matrius $\tilde{Q}_i$ són ortonormals.

Notem que les matrius $A^{(k)}$ són matrius semblants a l'original i, per tant, tenen els mateixos valors propis. Per altra banda, també és fàcil veure que les matrius $A^{(k)}$ són simètriques.

Notem a més, que si tenim la matriu $Q_k = R_{p_k,q_k}(\theta_k)$ els únics elements que canvien de la matriu $A^{(k)}$ respecte a la matriu precedent $A^{(k-1)}$ són els de les files $p_k$ i $q_k$ i els de les columnes $p_k$ i $q_k$.

&nbsp;

D'aquesta forma, l'objectiu del mètode serà trobar, a cada pas, la matriu de rotació $Q_k$ que fa que $A^{(k)}$ tendeixi a una matriu diagonal.

&nbsp;

#### **Com calculem el pla de rotació i quin angle hem de rotar?**

Suposem que estem al pas $k$-èssim del mètode i tenim la matriu $A^{(k)} = \left(a_{i,j}^{(k)}\right)_{1\leq i,j\leq n}$.


En el mètode clàssic de Jacobi busquem quin és l'element més gran en mòdul fora de la diagonal de la matriu $A^{(k)}$. ës a dir, suposarem que l'element $a_{p,q}^{(k)}$ és l'element més gran en mòdul del elements que no es troben a la diagonal de $A^{(k)}$:

$$
|a_{p,q}^{(k)}| = \max_{(i,j), i\neq j} |a_{i,j}^{(k)}| .
$$

Observem que $|a_{p,q}^{(k)}| > 0$, ja que en cas contrari tots els elements de la matriu fora de la diagonal serien 0 i, per tant, ja tindríem que la matriu $A^{(k)}$ és diagonal.

D'aquesta forma, considerarem la transformació:

$$
A^{(k+1)} = \underbrace{R_{p,q}(-\varphi)}_{\left(R_{p,q}(\varphi)\right)^\top}  A^{(k)} R_{p,q}(\varphi)
$$

Recordem que sabem que $A^{(k+1)}$ és simètrica i que només canviaran els elements de les files $p$ i $q$ de $A^{(k)}$.

En particular, tenim:

$$
\left\{
\begin{aligned}
a_{p,p}^{(k+1)} &= a_{p,p}^{(k)} \cos^2\varphi + 2a_{p,q}^{(k)}\cos\varphi\sin\varphi +  a_{q,q}^{(k)} \sin^2\varphi\\
a_{p,q}^{(k+1)} &= a_{q,p}^{(k+1)} = \left(a_{q,q}^{(k)} -a_{p,p}^{(k)}\right)\cos\varphi\sin\varphi + a_{p,q}^{(k)}\left(\cos^2\varphi-\sin^2\varphi\right)\\
a_{q,q}^{(k+1)} &= a_{p,p}^{(k)} \sin^2\varphi - 2a_{p,q}^{(k)}\cos\varphi\sin\varphi +  a_{q,q}^{(k)} \cos^2\varphi\\
\end{aligned}    
\right.    
$$

o bé, per $r\neq p,q$:

$$
\left\{
\begin{aligned}
a_{p,r}^{(k+1)} &= a_{p,r}^{(k)} \cos\varphi + a_{q,r}^{(k)}\sin\varphi\\
a_{q,r}^{(k+1)} &= -a_{p,r}^{(k)} \sin\varphi + a_{q,r}^{(k)}\cos\varphi\\
\end{aligned}    
\right.    
$$

Notem que d'aquesta manera tenim les files $p$ i $q$ i, per la simetria del problema, podem calcular els elements de les files $p$ i $q$.

&nbsp;

Triarem $\varphi$ de manera que $a_{p,q}^{(k+1)} = 0$, és a dir:

$$
0 = \left(a_{q,q}^{(k)} -a_{p,p}^{(k)}\right)\cos\varphi\sin\varphi + a_{p,q}^{(k)}\left(\cos^2\varphi-\sin^2\varphi\right)
$$

Dividint per $\cos^2\varphi$, tenim:

$$
\begin{aligned}
0 &= \frac{\left(a_{q,q}^{(k)} -a_{p,p}^{(k)}\right)\cos\varphi\sin\varphi + a_{p,q}^{(k)}\left(\cos^2\varphi-\sin^2\varphi\right)}{\cos^2\varphi}\\
& = \left(a_{q,q}^{(k)} -a_{p,p}^{(k)}\right)\frac{\sin\varphi}{\cos\varphi} + a_{p,q}^{(k)}\left(1-\frac{\sin^2\varphi}{\cos^2\varphi}\right)
\end{aligned}
$$

Anomenem $t = \cfrac{\sin\varphi}{\cos\varphi}$ i tenim la següent equació de segon grau:

$$
t^2 + \underbrace{\frac{a_{p,p}^{(k)} -a_{q,q}^{(k)}}{a_{p,q}^{(k)}}}_{=: 2\eta}t - 1 = 0
$$

i, per tant:

$$
t = -\eta \pm \sqrt{\eta^2+1}
$$

Així:

* Si $\eta > 0$ prenem $t = -\eta - \sqrt{\eta^2+1} < 0$, de manera que:

$$
\cos\varphi = \frac{1}{\sqrt{1+t^2}} > 0, \quad \sin\varphi = t\cos\varphi < 0.
$$

* Si $\eta < 0$ prenem $t = -\eta + \sqrt{\eta^2+1} > 0$, de manera que:

$$
\cos\varphi = \frac{1}{\sqrt{1+t^2}} > 0, \quad \sin\varphi = t\cos\varphi > 0.
$$

* Si $\eta = 0$ prenem $t = 1$, de manera que:

$$
\cos\varphi = \frac{\sqrt{2}}{2}, \quad \sin\varphi = \frac{\sqrt{2}}{2} > 0.
$$



&nbsp;

**Observació:** Observem que a cada iteració de $A^{(k)}$ a $A^{(k+1)}$ estem fent zeros dos valors $\left(a_{p,q}^{(k+1)} = a_{q,p}^{(k+1)} = 0\right)$ però introduïm contribucions no nul·les a posicions que abans eren 0.

#### **Mètode de Jacobi clàssic:**

Com hem dit, al pas $k$-èssim triarem l'element més gran en mòdul fora de la diagonal de $A^{(k)}$.

#### **Mètode cíclic de Jacobi**

Anem fent escombrades de la matriu en el següent ordre:

$$
\begin{matrix}(1,2) & (1,3) & \cdots & (1,n)\\ & (2,3) & \cdots & (2,n)\\ & & \ddots & \vdots \\ & & & (n-1,n)\end{matrix}
$$

Cada escombrada requereix un total de $\cfrac{n(n-1)}{2}$ rotacions.

### **Conclusió:**

La importància del mètode (o de la seva modificació) és que:

* $\displaystyle{\lim_{k\to \infty}A^{(k)} = D}$ (matriu diagonal amb valors propis)

* $\displaystyle{\lim_{k\to \infty}\tilde{Q}_k = P}$ (matriu amb els VEPs normalitzats per columnes)

&nbsp;

### *Exercici*

*Implementa una funció que, donada una matriu simètrica retorni els valors propis i els seus vectors propis.*

*De la mateixa manera, utilitzarem dos paràmetres opcionals:*

* `tol = 1.e-10`, la tolerància amb la que deixarem d'iterar si tots els elements de fora de la diagonal són més petits en mòdul a aquest valor.

* `maxIter = 1.e5`, el nombre màxim de rotacions que farem.

L'output del mètode ha de ser els, vaps, els veps i el nombre de rotacions fetes i, en cas de no trobar la solució amb la precissió dessitjada el nombre màxim de rotacions en negatiu.



In [ ]:
### Espai per fer l'exercici:
import numpy as np


# Feu la vostra funció aquí:
# l, V, iter = jacobi(A,tol=1.e-10,maxIter=1.e5)
def jacobi(A, tol=1.e-10,maxIter=1.e5):
    
    # Definim la matriu on guardarem les rotacions:
    Q = np.eye(len(A))

    for i in range(int(maxIter)):
        # Trobem l'element més gran en mòdul
        (p, q) = np.unravel_index(np.argmax(abs(np.triu(A, 1))), A.shape)
        
        # Triem l'angle de la rotació
        n = (A[p, p] - A[q, q])/(2*A[p, q])

        if (n > 0):
            t = -n - np.sqrt(n**2 + 1)
            cos = 1/np.sqrt(1 + t**2)
            sin = t*cos

        elif (n < 0):
            t = -n + np.sqrt(n**2 + 1)
            cos = 1/np.sqrt(1 + t**2)
            sin = t*cos

        # Si n == 0, sobreescrivim cos i sen
        if (n == 0):
            cos = sin = np.sqrt(2)/2

        # Definim la matriu de rotació i la guardem
        R = cos*np.eye(2)
        R[0, 1] = -sin
        R[1, 0] = sin

        Q[:, [p, q]] = Q[:, [p, q]]@R

        # Apliquem la rotació
#         app = A[p, p]*cos**2 + 2*A[p, q]*sin*cos + A[q, q]*sin**2
#         apq = (A[q, q] - A[p, p])*cos*sin + A[p, q]*(cos**2 - sin**2)
#         aqq = A[p, p]*sin**2 - 2*A[p, q]*sin*cos + A[q, q]*cos**2

# La cosa rara del cost lineal me da peores resultados, lo quito

        A[[p,q], :] = R.T@A[[p,q], :]

        # Evitem fer aquesta operació per tenir un cost lineal
        A[:, [p,q]] = A[:, [p, q]]@R

#         A[:, [p,q]] = A[[p,q], :].T.copy()
# 
#         A[p, p] = app
#         A[p, q] = apq
#         A[q, p] = apq
#         A[q, q] = aqq

        # Mirem si hem assolit la precisió desitjada
        if (np.max(np.triu(A, 1)) < tol):
            return np.diag(A), Q, i + 1
   
    # Si no trobem cap solució retornem les iteracions negatives
    return np.diag(A), Q, -(i + 1)






#################### PER TESTEJAR ####################

# Codi per testejar que funciona bé:
A = np.random.rand(3,3)
A = (A+A.T)/2 #Ara A és una matriu simètrica

# Funció de numpy per calcular els vaps i veps i perquè comproveu que teniu els mateixos resultats
vaps, veps = np.linalg.eigh(A) # Retorna els vaps i una matriu amb els veps normalitzats
print("||Id - P^T@P|| =", np.linalg.norm(np.eye(len(veps)) - veps.T@veps))

# Crideu la vostra funció:
VAPS, VEPS, iter = jacobi(A)
print("||Id - P^T@P|| =", np.linalg.norm(np.eye(len(VEPS)) - VEPS.T@VEPS))

print(VAPS)
print(vaps)

print(VEPS)
print(veps)

B = np.array([[2,1,0,2,1],
              [1,2,1,1,0],
              [0,1,0,1,0],
              [2,1,1,2,0],
              [1,0,0,0,0]],dtype=np.float64)

VAPS, VEPS, iter= jacobi(B)

result = 0

for i in VAPS: [Click to Close]

    result += abs(i)

print(result)

||Id - P^T@P|| = 1.2247002337688714e-15
n: -0.05057892685571608
n: -0.6135012633374586
n: 7.3847332549835505
n: 60.58557981004936
n: -700.9887659483336
n: 24001.293132167626
n: 152741054.84879854
||Id - P^T@P|| = 5.600498054374221e-16
[-0.60635261  1.67995972 -0.10267147]
[-0.60635261 -0.10267147  1.67995972]
[[ 0.06269131 -0.48851916  0.87029812]
 [-0.7407425  -0.60717766 -0.28746449]
 [ 0.66885749 -0.62664529 -0.39993167]]
[[ 0.06269131  0.87029812 -0.48851916]
 [-0.7407425  -0.28746449 -0.60717766]
 [ 0.66885749 -0.39993167 -0.62664529]]
n: 0.0
n: 0.7071067811865478
n: 2.175327747161076
n: -0.0
n: -0.8100663251043754
n: 5.250208038773867
n: 0.31815260332433304
n: 0.35534531939412467
n: 2.17931014900997
n: 7.198852748467919
n: 5.502973116754449
n: -4.377270015073627
n: 17.76337708452599
n: -28.081583694350254
n: -7.767896703798638
n: -70.10660069257179
n: -16.29395226981173
n: 119.07298910281568
n: 600.3835079898953
n: -516.8648891279885
n: 280.73087293960134
n: -2053.7683687607387
n

2 parts al examne

-teoria i problemes similar al parcial
- part de programació

PART PRO:

Vigilar que tenim medalla de tot
En el examen tindrem preguntas rollo:

Donat aquest sistema n*n calculeu la norma infinit de la solucio

Chill, resolem el sistema amb LU resolucio endavant, endarrere i fem norma
Coses així

Diu que penjara un fitxar amb quines fucions podem fer servir 
